<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { batchApi, genTypeApi, generationTypeConfigApi, settingsApi, taskApi } from '@/api/modules'
import { connectWs, onWsEvent } from '@/ws/client'
import GlassCard from '@/v2/components/GlassCard.vue'
import MediaViewer from '@/v2/components/MediaViewer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
import type { GenerationConfig, ParameterConfig, RuntimeWorkflow } from '@/v2/features/generation-config/model'
import { activeStatuses, statusMeta, type TaskOutput } from '@/v2/features/tasks/model'
import { useTaskOutputThumbs } from '@/v2/features/tasks/useTaskOutputThumbs'
import MediaParameterField from './MediaParameterField.vue'

type GenerationType = { id:number; code:string; name:string; media_type:'image'|'video'|'audio'; default_workflow_id:number|null; param_template:ParameterConfig[] }
type Row = { localId:number; params:Record<string,any>; paramCache:Record<string,Record<string,any>>; workflowVersionId:number|null; taskId:number|null; batchId:number|null; status:string; error:string|null; outputs:Array<TaskOutput&{thumbUrl?:string}> }
type SelectSetting = { label:string; options:Array<{label:string;value:any}>; default_value:any }

const route=useRoute();const loading=ref(true);const submitting=ref(false);const notice=ref('');const typeInfo=ref<GenerationType|null>(null);const config=ref<GenerationConfig|null>(null);const published=ref<number|null>(null);const runtimeWorkflows=ref<RuntimeWorkflow[]>([]);const settings=ref<Record<string,SelectSetting>>({});const rows=ref<Row[]>([]);const batchName=ref('');const importMode=ref<'append'|'replace'>('append');const importInput=ref<HTMLInputElement|null>(null);const preview=ref<TaskOutput|null>(null);let localId=0;let pollTimer:ReturnType<typeof setInterval>|null=null;let draftTimer:ReturnType<typeof setTimeout>|null=null;let offWs:(()=>void)|null=null;let draftReady=false;let activeDraftCode=''
const code=computed(()=>String(route.params.code||''));const isMotion=computed(()=>code.value==='motion_transfer');const title=computed(()=>config.value?.page?.title||typeInfo.value?.name||'创作生成');const description=computed(()=>config.value?.page?.description||'按行配置参数，支持单项或批量提交。');const busy=computed(()=>rows.value.some(r=>activeStatuses.includes(r.status)))
const defaultWorkflowVersion=computed(()=>runtimeWorkflows.value.find(v=>v.is_default)?.workflow_version_id||runtimeWorkflows.value[0]?.workflow_version_id||null)
const sizeSetting=computed(()=>settings.value[typeInfo.value?.media_type==='video'?'video_size':'image_size'])
const outputMediaType=computed(()=>typeInfo.value?.media_type||'image')
const {withThumbs,release}=useTaskOutputThumbs()

function randomSeed(){return Math.floor(Math.random()*4294967295)}
function workflowFor(versionId:number|null){return runtimeWorkflows.value.find(v=>v.workflow_version_id===versionId)||null}
function parametersFor(row:Row){return workflowFor(row.workflowVersionId)?.parameters||[]}
function schemesFor(row:Row){return workflowFor(row.workflowVersionId)?.parameter_schemes||[]}
function visibleParameters(row:Row){return parametersFor(row).filter(p=>{if(isMotion.value&&(p.key==='prompt'||p.key==='duration'))return false;if(p.key==='width'||p.key==='height')return false;return true})}
function hasSize(row:Row){const schema=parametersFor(row);return schema.some(p=>p.key==='width')&&schema.some(p=>p.key==='height')}
function defaultParams(versionId:number|null){const value:Record<string,any>={};const schema=workflowFor(versionId)?.parameters||[];for(const p of schema)value[p.key]=p.type==='seed'?randomSeed():(p.default??settings.value[p.options_from||'']?.default_value??(p.type==='bool'?false:null));const size=sizeSetting.value?.default_value;if(size&&schema.some(p=>p.key==='width')&&schema.some(p=>p.key==='height')){const [w,h]=String(size).split('x').map(Number);value.width=w;value.height=h;value.__size=size}const workflowSchemes=workflowFor(versionId)?.parameter_schemes||[];const scheme=workflowSchemes.find(v=>v.is_default)||workflowSchemes[0];if(isMotion.value&&scheme){value.__scheme=scheme.id;Object.assign(value,scheme.params)}return value}
function makeRow():Row{const versionId=defaultWorkflowVersion.value;return{localId:++localId,params:defaultParams(versionId),paramCache:{},workflowVersionId:versionId,taskId:null,batchId:null,status:'DRAFT',error:null,outputs:[]}}
function draftKey(target=activeDraftCode||code.value){return `v2-generate-draft:${target}`}
function saveLocalDraft(){if(!draftReady||!activeDraftCode)return;const savedRows=rows.value.map(row=>({...row,outputs:[]}));sessionStorage.setItem(draftKey(),JSON.stringify({batchName:batchName.value,importMode:importMode.value,rows:savedRows,savedAt:Date.now()}))}
function restoreLocalDraft(){try{const raw=sessionStorage.getItem(draftKey());if(!raw)return false;const saved=JSON.parse(raw);if(!Array.isArray(saved.rows)||!saved.rows.length)return false;rows.value=saved.rows.map((row:any)=>{const versionId=runtimeWorkflows.value.some(v=>v.workflow_version_id===row.workflowVersionId)?row.workflowVersionId:defaultWorkflowVersion.value;return{...row,localId:++localId,workflowVersionId:versionId,params:row.params||defaultParams(versionId),paramCache:row.paramCache||{},outputs:[]}});batchName.value=String(saved.batchName||'');importMode.value=saved.importMode==='replace'?'replace':'append';if(rows.value.some(row=>row.taskId&&activeStatuses.includes(row.status)))startPoll();notice.value='已恢复刷新前未完成的页面数据';return true}catch{return false}}
function cloneRow(row:Row){const next=makeRow();next.params=JSON.parse(JSON.stringify(row.params));next.paramCache=JSON.parse(JSON.stringify(row.paramCache));next.workflowVersionId=row.workflowVersionId;rows.value.push(next)}
function removeRow(index:number){if(rows.value.length===1){rows.value=[makeRow()];return}rows.value.splice(index,1)}
function optionList(p:ParameterConfig){return p.options||settings.value[p.options_from||'']?.options||[]}
function visible(p:ParameterConfig,row:Row){const rule=p.visible_when;if(rule){const v=row.params[rule.key];if(rule.operator==='truthy'&&!v)return false;if(rule.operator==='equals'&&v!==rule.value)return false;if(rule.operator==='not_equals'&&v===rule.value)return false}const match=p.key.match(/^reference_image_(\d)$/);if(match)return Boolean(row.params.multi_reference_enabled)&&Number(match[1])<=Number(row.params.multi_reference_count||1);return true}
function setSize(row:Row,value:string){row.params.__size=value;const [w,h]=String(value).split('x').map(Number);row.params.width=w;row.params.height=h}
function switchWorkflow(row:Row,value:any){const nextId=Number(value)||null;if(nextId===row.workflowVersionId)return;const previousId=row.workflowVersionId;const previousParams=JSON.parse(JSON.stringify(row.params));if(previousId)row.paramCache[String(previousId)]=previousParams;const next=defaultParams(nextId);const nextSchema=workflowFor(nextId)?.parameters||[];const oldByKey=new Map(parametersFor(row).map(item=>[item.key,item]));for(const parameter of nextSchema){const old=oldByKey.get(parameter.key);if(old&&old.type===parameter.type&&previousParams[parameter.key]!==undefined)next[parameter.key]=previousParams[parameter.key]}Object.assign(next,row.paramCache[String(nextId)]||{});row.workflowVersionId=nextId;row.params=next}
function applyScheme(row:Row,id:any){row.params.__scheme=id;const scheme=schemesFor(row).find(v=>String(v.id)===String(id));if(scheme)Object.assign(row.params,scheme.params)}
function cleanParams(row:Row){const result:Record<string,any>={};for(const parameter of parametersFor(row)){const value=row.params[parameter.key];if(value!==null&&value!==''&&value!==undefined)result[parameter.key]=value}return result}
function validate(row:Row){if(!row.workflowVersionId)return '没有可用工作流';for(const p of parametersFor(row)){if(!visible(p,row))continue;if(p.required&&(row.params[p.key]===null||row.params[p.key]===undefined||row.params[p.key]===''))return `请填写${p.label}`}return ''}
function errorText(e:any){return e?.response?.data?.detail||e?.response?.data?.message||e?.message||'操作失败'}

async function load(){saveLocalDraft();if(draftTimer)clearTimeout(draftTimer);draftReady=false;activeDraftCode=code.value;loading.value=true;notice.value='';rows.value.forEach(row=>release(row.outputs));rows.value=[];try{const [types,selectOptions]=await Promise.all([genTypeApi.list({enabled:true}),settingsApi.getSelectOptions()]);settings.value=selectOptions||{};typeInfo.value=(types as GenerationType[]).find(v=>v.code===code.value)||null;if(!typeInfo.value)throw new Error('生成类型不存在或已停用');const active=await generationTypeConfigApi.active(typeInfo.value.id);config.value=active.config;published.value=active.published_version_id;runtimeWorkflows.value=(active.workflows||[]) as RuntimeWorkflow[];if(isMotion.value&&runtimeWorkflows.value.length&&!runtimeWorkflows.value.some(v=>v.parameter_schemes?.length)){const legacySchemes=config.value?.parameter_schemes?.length?config.value.parameter_schemes:await genTypeApi.motionTransferSchemes();runtimeWorkflows.value.forEach(v=>v.parameter_schemes=legacySchemes);}if(!restoreLocalDraft()){rows.value=[makeRow()];batchName.value=`${typeInfo.value.name}-${new Date().toLocaleString()}`}if(!runtimeWorkflows.value.length)notice.value='当前生成类型还没有可用工作流，请先在生成类型配置中上传、配置参数并发布。'}catch(e:any){typeInfo.value=null;notice.value=errorText(e)}finally{draftReady=true;loading.value=false}}

async function createBatch(target:Row[],submit:boolean){if(!typeInfo.value)return null;for(const row of target){const message=validate(row);if(message)throw new Error(`第 ${rows.value.indexOf(row)+1} 行：${message}`)}const batch=await batchApi.create({name:batchName.value,generation_type_id:typeInfo.value.id,rows:target.map((row,index)=>({row_no:index,generation_type_id:typeInfo.value!.id,workflow_version_id:row.workflowVersionId,params:cleanParams(row)}))});for(const row of target)row.batchId=batch.id;if(!submit)return batch;const result=await batchApi.submit(batch.id);const tasks=await batchApi.rows(batch.id);target.forEach((row,index)=>{const task=tasks[index];row.taskId=task?.id||null;row.status=task?.status||'PENDING';row.error=task?.error||null});notice.value=`批次 #${batch.id} 已提交：${result.enqueued} 项进入队列${result.invalid?`，${result.invalid} 项无效`:''}`;startPoll();return batch}
async function submitAll(){submitting.value=true;try{await createBatch(rows.value,true)}catch(e:any){notice.value=errorText(e)}finally{submitting.value=false}}
async function submitOne(row:Row){submitting.value=true;try{await createBatch([row],true)}catch(e:any){notice.value=errorText(e)}finally{submitting.value=false}}
async function saveDraft(){submitting.value=true;try{const batch=await createBatch(rows.value,false);if(batch)notice.value=`草稿批次 #${batch.id} 已保存，可在批次任务中查看。`}catch(e:any){notice.value=errorText(e)}finally{submitting.value=false}}
async function refreshRows(){const pending=rows.value.filter(r=>r.taskId&&(activeStatuses.includes(r.status)||(r.status==='SUCCESS'&&!r.outputs.length)));await Promise.all(pending.map(async row=>{try{const task=await taskApi.get(row.taskId!);row.status=task.status;row.error=task.error;if(task.status==='SUCCESS'&&!row.outputs.length)await loadOutputs(row)}catch{}}));if(!busy.value&&!rows.value.some(r=>r.status==='SUCCESS'&&!r.outputs.length))stopPoll()}
async function loadOutputs(row:Row){if(!row.taskId)return;const list=await taskApi.outputs(row.taskId);release(row.outputs);row.outputs=await withThumbs(list)}
function startPoll(){if(!pollTimer)pollTimer=setInterval(()=>void refreshRows(),2000)}function stopPoll(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
async function importPrompts(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const lines=(await file.text()).split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!lines.length){notice.value='导入文件没有有效提示词';return}const added=lines.map(prompt=>{const row=makeRow();row.params.prompt=prompt;return row});rows.value=importMode.value==='replace'?added:[...rows.value,...added];notice.value=`已${importMode.value==='replace'?'替换为':'追加'} ${added.length} 条提示词，其他参数使用页面默认值。`;(event.target as HTMLInputElement).value=''}
watch([batchName,importMode,rows],()=>{if(!draftReady)return;if(draftTimer)clearTimeout(draftTimer);draftTimer=setTimeout(saveLocalDraft,250)},{deep:true})
watch(code,load);onMounted(()=>{window.addEventListener('beforeunload',saveLocalDraft);void load();connectWs();offWs=onWsEvent(()=>void refreshRows())});onBeforeUnmount(saveLocalDraft);onUnmounted(()=>{window.removeEventListener('beforeunload',saveLocalDraft);stopPoll();if(draftTimer)clearTimeout(draftTimer);offWs?.()})
</script>

<template>
  <div class="v2-page generate-page">
    <div class="v2-page-heading heading"><div><div class="eyebrow"><StatusBadge tone="info">动态配置</StatusBadge><StatusBadge :tone="published?'success':'warning'">{{ published?`已发布配置 #${published}`:'兼容配置' }}</StatusBadge></div><h1>{{ title }}</h1><p>{{ description }}</p></div><div class="heading-actions"><V2Button variant="ghost" @click="load">重新载入</V2Button><V2Button variant="primary" :disabled="submitting||loading||!rows.length" @click="submitAll">{{ submitting?'提交中…':`全部生成（${rows.length}）` }}</V2Button></div></div>
    <div v-if="notice" class="notice" :class="{danger:!typeInfo}">{{ notice }}</div>
    <GlassCard v-if="!loading&&typeInfo" padding="sm"><div class="batch-tools"><V2Field label="批次名称"><input v-model="batchName" /></V2Field><V2Field label="提示词导入方式"><select v-model="importMode"><option value="append">追加到现有任务行</option><option value="replace">清空后导入</option></select></V2Field><input ref="importInput" hidden type="file" accept=".txt,.csv,text/plain" @change="importPrompts"/><V2Button variant="ghost" @click="importInput?.click()">导入提示词</V2Button><V2Button variant="ghost" @click="rows.push(makeRow())">新增任务行</V2Button><V2Button :disabled="submitting" @click="saveDraft">保存草稿</V2Button></div><small class="import-help">导入格式：每行一条提示词；尺寸、种子、工作流等使用页面当前默认值。</small></GlassCard>
    <div v-if="loading" class="loading-state">正在读取生成配置…</div>
    <div v-else class="rows"><GlassCard v-for="(row,index) in rows" :key="row.localId" padding="sm"><header class="row-head"><div><span class="row-no">{{ String(index+1).padStart(2,'0') }}</span><div><b>任务行 {{ index+1 }}</b><small v-if="row.taskId">任务 #{{ row.taskId }} · 批次 #{{ row.batchId }}</small><small v-else>尚未提交</small></div></div><div><StatusBadge :tone="statusMeta[row.status]?.tone||'neutral'">{{ statusMeta[row.status]?.label||row.status }}</StatusBadge><V2Button variant="ghost" @click="cloneRow(row)">复制</V2Button><V2Button variant="ghost" @click="removeRow(index)">删除</V2Button></div></header>
      <div class="row-body"><div class="parameter-grid">
        <V2Field label="工作流" required><select :value="row.workflowVersionId" :disabled="activeStatuses.includes(row.status)" @change="switchWorkflow(row,($event.target as HTMLSelectElement).value)"><option :value="null">请选择工作流</option><option v-for="workflow in runtimeWorkflows" :key="workflow.workflow_version_id" :value="workflow.workflow_version_id">{{ workflow.name }} · v{{ workflow.version }}</option></select></V2Field>
        <V2Field v-if="isMotion&&schemesFor(row).length" label="参数方案" required><select :value="row.params.__scheme" @change="applyScheme(row,($event.target as HTMLSelectElement).value)"><option v-for="scheme in schemesFor(row)" :key="scheme.id" :value="scheme.id">{{ scheme.name }}{{ scheme.is_default?'（默认）':'' }}</option></select></V2Field>
        <V2Field v-if="hasSize(row)&&sizeSetting" :label="outputMediaType==='video'?'视频尺寸':'图片尺寸'"><select :value="row.params.__size" @change="setSize(row,($event.target as HTMLSelectElement).value)"><option v-for="option in sizeSetting.options" :key="option.value" :value="option.value">{{ option.label }}</option></select></V2Field>
        <template v-for="parameter in visibleParameters(row)" :key="parameter.key"><V2Field v-if="visible(parameter,row)" :label="parameter.label||parameter.key" :hint="parameter.help||(parameter.unit?`单位：${parameter.unit}`:undefined)" :required="parameter.required" :class="{'wide-field':['textarea','image','video','audio'].includes(parameter.type)}">
          <textarea v-if="parameter.type==='textarea'" v-model="row.params[parameter.key]" rows="3" :disabled="activeStatuses.includes(row.status)" />
          <select v-else-if="parameter.type==='select'||parameter.type==='size'" v-model="row.params[parameter.key]" :disabled="activeStatuses.includes(row.status)"><option v-for="option in optionList(parameter)" :key="String(option.value)" :value="option.value">{{ option.label }}</option></select>
          <label v-else-if="parameter.type==='bool'" class="switch"><input v-model="row.params[parameter.key]" type="checkbox" :disabled="activeStatuses.includes(row.status)"/><span/><b>{{ row.params[parameter.key]?'已开启':'已关闭' }}</b></label>
          <MediaParameterField v-else-if="['image','video','audio'].includes(parameter.type)" v-model="row.params[parameter.key]" :media-type="parameter.type as 'image'|'video'|'audio'" :multiple="parameter.multiple" :disabled="activeStatuses.includes(row.status)" />
          <div v-else-if="parameter.type==='seed'" class="seed-input"><input v-model.number="row.params[parameter.key]" type="number"/><V2Button variant="ghost" @click="row.params[parameter.key]=randomSeed()">随机</V2Button></div>
          <input v-else :value="row.params[parameter.key]" :type="['int','float','slider'].includes(parameter.type)?'number':'text'" :min="parameter.min" :max="parameter.max" :step="parameter.step||(parameter.type==='int'?1:'any')" :disabled="activeStatuses.includes(row.status)" @input="row.params[parameter.key]=['int','float','slider'].includes(parameter.type)?Number(($event.target as HTMLInputElement).value):($event.target as HTMLInputElement).value"/>
        </V2Field></template>
      </div><aside class="result"><div class="result-head"><b>执行结果</b><span v-if="row.error">{{ row.error }}</span><span v-else>{{ statusMeta[row.status]?.label||'等待生成' }}</span></div><div v-if="row.outputs.length" class="output-grid"><button v-for="output in row.outputs" :key="output.id" @click="preview=output"><img v-if="output.media_type!=='audio'" :src="output.thumbUrl"/><span v-else>♪</span><i v-if="output.media_type==='video'">▶</i></button></div><div v-else class="empty-output"><span>{{ outputMediaType==='image'?'▧':outputMediaType==='video'?'▶':'♪' }}</span><small>{{ activeStatuses.includes(row.status)?'任务执行中，结果会自动刷新':'生成结果将在这里显示' }}</small></div><V2Button variant="primary" :disabled="submitting||activeStatuses.includes(row.status)" @click="submitOne(row)">生成此项</V2Button></aside></div>
    </GlassCard></div>
    <MediaViewer :open="!!preview" :output="preview" @close="preview=null"/>
  </div>
</template>

<style scoped>
.generate-page{max-width:1540px}.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.heading h1{margin-top:14px}.eyebrow,.heading-actions{display:flex;align-items:center;gap:8px}.notice{margin:-8px 0 16px;padding:11px 14px;color:#dbe4ff;background:rgba(94,120,237,.13);border:1px solid rgba(130,149,255,.22);border-radius:12px}.notice.danger{color:#ffdce1;background:rgba(255,127,145,.1)}.batch-tools{display:grid;grid-template-columns:minmax(240px,1fr) 200px auto auto auto;align-items:end;gap:9px}.import-help{display:block;margin-top:10px;color:var(--v2-text-subtle)}.loading-state{padding:90px;text-align:center;color:var(--v2-text-muted)}.rows{margin-top:14px;display:grid;gap:14px}.row-head,.row-head>div{display:flex;align-items:center;justify-content:space-between;gap:9px}.row-head{padding-bottom:12px;border-bottom:1px solid var(--v2-border)}.row-head>div:first-child>div{display:grid;gap:4px}.row-head small{color:var(--v2-text-subtle)}.row-no{width:38px;height:38px;display:grid;place-items:center;color:#dfe5ff;background:rgba(130,149,255,.14);border:1px solid var(--v2-border);border-radius:10px;font-weight:800}.row-body{padding-top:14px;display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:14px}.parameter-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-content:start;gap:12px}.wide-field{grid-column:span 3}.result{min-height:230px;padding:13px;display:flex;flex-direction:column;gap:11px;background:rgba(3,12,25,.28);border:1px solid var(--v2-border);border-radius:14px}.result-head{display:grid;gap:4px}.result-head span{color:var(--v2-text-subtle);font-size:11px;word-break:break-word}.empty-output{flex:1;display:grid;place-items:center;align-content:center;gap:9px;color:var(--v2-text-muted)}.empty-output span{font-size:32px}.output-grid{flex:1;display:grid;grid-template-columns:repeat(2,1fr);align-content:start;gap:7px}.output-grid button{height:100px;padding:0;position:relative;overflow:hidden;color:var(--v2-text);background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:9px;cursor:pointer}.output-grid img{width:100%;height:100%;object-fit:contain}.output-grid i{position:absolute;inset:0;display:grid;place-items:center;font-size:24px;text-shadow:0 2px 4px #000}.switch{height:42px;padding:0 11px;display:flex;align-items:center;gap:9px;background:rgba(3,12,25,.42);border:1px solid var(--v2-border);border-radius:10px}.switch input{display:none}.switch span{width:34px;height:19px;padding:2px;background:#536176;border-radius:20px}.switch span:after{content:'';display:block;width:15px;height:15px;background:white;border-radius:50%;transition:.2s}.switch input:checked+span{background:var(--v2-primary)}.switch input:checked+span:after{transform:translateX(15px)}.switch b{font-size:12px}.seed-input{display:grid;grid-template-columns:1fr auto;gap:7px}
@media(max-width:1120px){.batch-tools{grid-template-columns:1fr 1fr auto}.row-body{grid-template-columns:1fr}.result{min-height:170px}.parameter-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.wide-field{grid-column:span 2}}
@media(max-width:700px){.heading{align-items:flex-start;flex-direction:column}.heading-actions{width:100%}.heading-actions>*{flex:1}.batch-tools{grid-template-columns:1fr 1fr}.batch-tools>*:first-child{grid-column:span 2}.row-head{align-items:flex-start;flex-direction:column}.row-head>div:last-child{width:100%;flex-wrap:wrap;justify-content:flex-start}.parameter-grid{grid-template-columns:1fr}.wide-field{grid-column:auto}.result{min-height:190px}.output-grid button{height:120px}}
.output-grid button{height:auto;aspect-ratio:2/3}
</style>
