<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { nodeApi, runtimeApi, taskApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'

const runtime=ref<any>(null);const nodes=ref<any[]>([]);const active=ref<any[]>([]);const loading=ref(true);const message=ref('');let timer:ReturnType<typeof setInterval>|null=null
function date(value:string|null){return value?new Date(value).toLocaleString():'—'}
async function load(){try{const [r,n,t]=await Promise.all([runtimeApi.dispatcher(),nodeApi.list(),taskApi.list({active:true})]);runtime.value=r;nodes.value=n;active.value=t}finally{loading.value=false}}
async function probe(id:number){try{await nodeApi.probe(id);message.value='节点探测成功'}catch(e:any){message.value=e.response?.data?.message||'节点探测失败'}await load()}
async function release(id:number){if(!confirm(`确认释放任务 #${id} 的执行槽？`))return;await runtimeApi.release(id);message.value='执行槽已释放';await load()}
async function resubmit(id:number){await runtimeApi.resubmit(id);message.value='任务已重新提交';await load()}
onMounted(()=>{load();timer=setInterval(load,5000)});onUnmounted(()=>{if(timer)clearInterval(timer)})
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge :tone="runtime?.running?'success':'danger'">{{ runtime?.running?'调度器运行中':'调度器已停止' }}</StatusBadge><h1>运行监控</h1><p>监控独立调度线程、ComfyUI 节点和占用执行槽的任务。</p></div><V2Button @click="load">立即刷新</V2Button></div><p v-if="message" class="message">{{message}}</p><div v-if="loading" class="empty">加载中…</div><template v-else><div class="metrics"><GlassCard><span>心跳</span><strong>{{date(runtime?.last_heartbeat_at)}}</strong><small>{{runtime?.thread_name||'—'}}</small></GlassCard><GlassCard><span>调度轮次</span><strong>{{runtime?.counters.ticks||0}}</strong><small>最近 {{date(runtime?.last_tick_at)}}</small></GlassCard><GlassCard><span>累计提交</span><strong>{{runtime?.counters.submitted||0}}</strong><small>完成 {{runtime?.counters.completed||0}} · 失败 {{runtime?.counters.failed||0}}</small></GlassCard><GlassCard><span>待处理</span><strong>{{runtime?.tasks.PENDING||0}}</strong><small>排队 {{runtime?.tasks.QUEUED||0}} · 运行 {{runtime?.tasks.RUNNING||0}}</small></GlassCard></div><GlassCard><div class="section-head"><h2>ComfyUI 节点</h2><span>最近自动探测 {{date(runtime?.last_probe_at)}}</span></div><div class="node-list"><article v-for="node in nodes" :key="node.id"><div><b>{{node.name}}</b><code>{{node.base_url}}</code></div><StatusBadge :tone="node.status==='online'?'success':node.status==='degraded'?'warning':'danger'">{{node.status}}</StatusBadge><span>失败 {{node.consecutive_failures||0}} 次</span><span>最近在线 {{date(node.last_seen_at)}}</span><small>{{node.health_error||'连接正常'}}</small><V2Button @click="probe(node.id)">立即探测</V2Button></article></div></GlassCard><GlassCard><div class="section-head"><h2>执行中任务</h2><span>{{active.length}} 项</span></div><div class="task-list"><article v-for="task in active" :key="task.id"><b>#{{task.id}}</b><StatusBadge tone="info">{{task.status}}</StatusBadge><span>节点 #{{task.node_id||'—'}}</span><code>{{task.prompt_id||'尚未提交'}}</code><small>{{task.error||'运行正常'}}</small><div><V2Button v-if="['DISPATCHING','QUEUED','RUNNING'].includes(task.status)" variant="danger" @click="release(task.id)">释放执行槽</V2Button><V2Button v-if="['FAILED','CANCELLED'].includes(task.status)" @click="resubmit(task.id)">重新提交</V2Button></div></article><p v-if="!active.length" class="empty">当前没有执行中任务</p></div></GlassCard><p v-if="runtime?.last_error" class="runtime-error">最近调度错误：{{runtime.last_error}}</p></template></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between}.heading h1{margin-top:14px}.message{color:var(--v2-success)}.metrics{margin:16px 0;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metrics section{display:grid;gap:8px}.metrics span,.metrics small,.section-head span{color:var(--v2-text-muted)}.metrics strong{font-size:24px}.section-head{display:flex;align-items:center;justify-content:space-between}.node-list,.task-list{display:grid;gap:8px}.node-list article,.task-list article{padding:12px;display:grid;grid-template-columns:1.2fr auto auto 1fr 1.5fr auto;align-items:center;gap:12px;background:var(--v2-surface-soft);border-radius:11px}.node-list article>div{display:grid;gap:4px}.node-list code,.task-list code,.node-list small,.task-list small{color:var(--v2-text-subtle);overflow:hidden;text-overflow:ellipsis}.runtime-error{color:var(--v2-danger)}.empty{text-align:center;color:var(--v2-text-muted)}section+section{margin-top:14px}@media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.node-list article,.task-list article{grid-template-columns:1fr 1fr}.node-list small,.task-list small{grid-column:1/-1}}@media(max-width:650px){.heading{align-items:flex-start;flex-direction:column;gap:12px}.metrics{grid-template-columns:1fr}.node-list article,.task-list article{grid-template-columns:1fr}.node-list small,.task-list small{grid-column:auto}}</style>
