<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { genTypeApi, taskApi } from '@/api/modules'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import MediaViewer from '@/v2/components/MediaViewer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
import { formatDate, statusMeta, type GenerationTypeItem, type TaskEvent, type TaskItem, type TaskOutput } from './model'
import { useTaskOutputThumbs } from './useTaskOutputThumbs'
import './task-output-thumbnails.css'
const props=defineProps<{open:boolean;task:TaskItem|null}>();const emit=defineEmits<{close:[];changed:[]}>()
const detail=ref<TaskItem|null>(null);const events=ref<TaskEvent[]>([]);const outputs=ref<TaskOutput[]>([]);const types=ref<GenerationTypeItem[]>([]);const draft=ref<Record<string,any>>({});const loading=ref(false);const executing=ref(false);const preview=ref<TaskOutput|null>(null)
const {withThumbs,release}=useTaskOutputThumbs()
const typeInfo=computed(()=>types.value.find(v=>v.id===detail.value?.generation_type_id));const mediaKeys=computed(()=>new Set((typeInfo.value?.param_schema||[]).filter(v=>['image','video','audio'].includes(v.type||'')).map(v=>v.key)))
const editableEntries=computed(()=>Object.entries(draft.value).filter(([k])=>!mediaKeys.value.has(k)));const mediaEntries=computed(()=>Object.entries(detail.value?.params||{}).filter(([k])=>mediaKeys.value.has(k)))
async function load(){if(!props.open||!props.task)return;loading.value=true;try{const menu=await genTypeApi.menu();types.value=[...(menu.image||[]),...(menu.video||[]),...(menu.audio||[])];const [item,ev,out]=await Promise.all([taskApi.get(props.task.id),taskApi.events(props.task.id),taskApi.outputs(props.task.id)]);detail.value=item;events.value=ev;release(outputs.value);outputs.value=await withThumbs(out);draft.value=structuredClone(item.params||{})}finally{loading.value=false}}
watch(()=>[props.open,props.task?.id],load)
function label(key:string){return typeInfo.value?.param_schema?.find(v=>v.key===key)?.label||key} function resourceOutput(value:unknown,key:string):TaskOutput|null{const id=Number(typeof value==='object'&&value?Object.values(value as object)[0]:value);if(!id)return null;const type=(typeInfo.value?.param_schema?.find(v=>v.key===key)?.type||'image') as TaskOutput['media_type'];return{id,filename:`${label(key)} #${id}`,media_type:type,mime:type==='image'?'image/*':type==='video'?'video/*':'audio/*'}}
async function execute(){if(!detail.value)return;executing.value=true;try{const created=await taskApi.execute(detail.value.id,draft.value);globalThis.alert(`已创建新任务 #${created.id}`);emit('changed');emit('close')}catch(e:any){globalThis.alert(e.response?.data?.detail||'执行失败')}finally{executing.value=false}}
</script>
<template><GlassDrawer :open="open" :title="detail?`任务 #${detail.id}`:'任务详情'" @close="emit('close')"><div v-if="loading" class="loading">加载详情…</div><div v-else-if="detail" class="detail"><div class="summary"><StatusBadge :tone="statusMeta[detail.status]?.tone">{{ statusMeta[detail.status]?.label||detail.status }}</StatusBadge><span>批次 #{{ detail.batch_id }} · 行 {{ detail.row_no }}</span></div><section><h3>运行信息</h3><dl><div><dt>工作流版本</dt><dd>#{{ detail.workflow_version_id||'—' }}</dd></div><div><dt>执行节点</dt><dd>#{{ detail.node_id||'—' }}</dd></div><div><dt>Prompt ID</dt><dd>{{ detail.prompt_id||'—' }}</dd></div><div><dt>创建时间</dt><dd>{{ formatDate(detail.created_at) }}</dd></div><div><dt>开始时间</dt><dd>{{ formatDate(detail.started_at) }}</dd></div><div><dt>完成时间</dt><dd>{{ formatDate(detail.finished_at) }}</dd></div></dl><p v-if="detail.error" class="error">{{ detail.error }}</p></section><section v-if="mediaEntries.length"><h3>多媒体输入</h3><div class="media-inputs"><button v-for="([key,value]) in mediaEntries" :key="key" @click="preview=resourceOutput(value,key)"><b>{{ label(key) }}</b><span>{{ resourceOutput(value,key)?.media_type }} #{{ resourceOutput(value,key)?.id }}</span><i>预览 ›</i></button></div></section><section><h3>任务参数</h3><div class="params"><V2Field v-for="([key,value]) in editableEntries" :key="key" :label="label(key)"><input v-if="typeof value==='number'" v-model.number="draft[key]" type="number"/><select v-else-if="typeof value==='boolean'" v-model="draft[key]"><option :value="true">开启</option><option :value="false">关闭</option></select><textarea v-else-if="typeof value==='object'" :value="JSON.stringify(value,null,2)" rows="4" @input="draft[key]=($event.target as HTMLTextAreaElement).value"/><textarea v-else v-model="draft[key]" rows="2"/></V2Field></div><V2Button variant="primary" :disabled="executing" @click="execute">{{ executing?'创建中…':'使用修改参数执行' }}</V2Button><small class="note">执行会创建新任务，原任务保持不变；多媒体参数不可修改。</small></section><section><h3>执行时间线</h3><div class="timeline"><div v-for="event in events" :key="event.id"><i/><span><b>{{ event.type }}</b><small>{{ event.progress }}% · {{ formatDate(event.created_at) }}</small></span></div><p v-if="!events.length">暂无事件记录</p></div></section><section><h3>执行结果（{{ outputs.length }}）</h3><div class="outputs"><button v-for="out in outputs" :key="out.id" @click="preview=out"><img v-if="out.media_type!=='audio'" :src="out.thumbUrl" :alt="out.filename"/><span v-else>♪</span><b>{{ out.filename }}</b></button><p v-if="!outputs.length">暂无输出</p></div></section></div><MediaViewer :open="!!preview" :output="preview" @close="preview=null"/></GlassDrawer></template>
<style scoped>.loading{padding:50px;text-align:center;color:var(--v2-text-muted)}.detail{display:grid;gap:20px}.summary{display:flex;align-items:center;justify-content:space-between;color:var(--v2-text-muted)}section{padding-top:4px;border-top:1px solid var(--v2-border)}h3{font-size:14px;margin:16px 0 12px}dl{margin:0;display:grid;grid-template-columns:1fr 1fr;gap:10px}dl div{padding:10px;background:var(--v2-surface-soft);border-radius:10px}dt{font-size:11px;color:var(--v2-text-subtle)}dd{margin:5px 0 0;overflow-wrap:anywhere}.error{padding:10px;color:var(--v2-danger);background:rgba(255,127,145,.1);border-radius:10px}.params{display:grid;gap:14px;margin-bottom:14px}.note{display:block;margin-top:10px;color:var(--v2-text-subtle)}.media-inputs,.outputs{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.media-inputs button,.outputs button{min-height:66px;padding:10px;color:var(--v2-text);background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:11px;text-align:left;cursor:pointer}.media-inputs button{display:grid;gap:4px}.media-inputs span,.media-inputs i{color:var(--v2-text-muted);font-size:11px;font-style:normal}.outputs img{width:100%;height:100px;object-fit:contain;background:rgba(0,0,0,.2);border-radius:8px}.outputs button>b{display:block;margin-top:7px;overflow:hidden;text-overflow:ellipsis}.timeline{display:grid;gap:8px}.timeline>div{display:flex;gap:10px}.timeline i{width:8px;height:8px;margin-top:6px;border-radius:50%;background:var(--v2-primary)}.timeline span{display:grid}.timeline small,.timeline p,.outputs p{color:var(--v2-text-muted)}@media(max-width:420px){dl,.media-inputs,.outputs{grid-template-columns:1fr}}</style>
