import type { RouteRecordRaw } from 'vue-router'

export const v2Routes: RouteRecordRaw = {
  path: '/v2',
  component: () => import('@/v2/app/V2AppShell.vue'),
  meta: { requiresV2: true },
  children: [
    { path: 'drama/projects/:projectId/episodes/:episodeId/director', name: 'v2-drama-director-workspace', component: () => import('@/v2/features/short-drama/DramaDirectorWorkspace.vue'), meta: { title: '导演工作台', requiresShortDrama: true } },
    { path: 'drama/projects/:projectId/episodes/:episodeId/spatial', name: 'v2-drama-spatial-storyboard', component: () => import('@/v2/features/short-drama/DramaSpatialStoryboardView.vue'), meta: { title: '空间走位与分镜', requiresShortDrama: true } },
    { path: 'drama/projects/:projectId/episodes/:episodeId/quality', name: 'v2-drama-quality-gate', component: () => import('@/v2/features/short-drama/DramaQualityGateView.vue'), meta: { title: '质检与交付', requiresShortDrama: true } },
    { path: 'drama/projects/:projectId/episodes/:episodeId/script', name: 'v2-drama-episode-script', component: () => import('@/v2/features/short-drama/DramaEpisodeScriptView.vue'), meta: { title: '剧本策划', requiresShortDrama: true } },
    { path: 'drama/projects/:projectId/episodes/:episodeId/manifest', name: 'v2-drama-script-manifest', component: () => import('@/v2/features/short-drama/DramaScriptManifestView.vue'), meta: { title: '拍摄清单', requiresShortDrama: true } },
    { path: 'drama/projects/:projectId/assets', name: 'v2-drama-assets-casting', component: () => import('@/v2/features/short-drama/DramaAssetsCastingView.vue'), meta: { title: '角色与场景', requiresShortDrama: true } },
    { path: 'drama/projects/:id/production', name: 'v2-drama-production', component: () => import('@/v2/features/short-drama/ShortDramaProductionView.vue'), meta: { title: '镜头生产', requiresShortDrama: true } },
    { path: 'drama/projects/:id/import', name: 'v2-drama-import', component: () => import('@/v2/features/short-drama/ShortDramaImportView.vue'), meta: { title: '文档导入', requiresShortDrama: true } },
    { path: '', name: 'v2-home', component: () => import('@/v2/features/dashboard/DashboardView.vue'), meta: { title: '系统概览' } },
    { path: 'drama/projects', name: 'v2-drama-projects', component: () => import('@/v2/features/short-drama/ShortDramaProjectListView.vue'), meta: { title: '短剧项目', requiresShortDrama: true } },
    { path: 'drama/new', name: 'v2-drama-new', component: () => import('@/v2/features/short-drama/ShortDramaProjectCreateView.vue'), meta: { title: '新建短剧', requiresShortDrama: true } },
    { path: 'drama/projects/:id', name: 'v2-drama-overview', component: () => import('@/v2/features/short-drama/ShortDramaProjectOverviewView.vue'), meta: { title: '项目概览', requiresShortDrama: true } },
    { path: 'design-system', name: 'v2-design-system', component: () => import('@/v2/features/design-system/DesignSystemView.vue'), meta: { title: '组件规范' } },
    { path: 'generate/:code', name: 'v2-generate', component: () => import('@/v2/features/generate/DynamicGenerateView.vue'), meta: { title: '创作生成' } },
    { path: 'tasks', name: 'v2-tasks', component: () => import('@/v2/features/tasks/TaskListView.vue'), meta: { title: '任务管理' } },
    { path: 'batches', name: 'v2-batches', component: () => import('@/v2/features/batches/BatchListView.vue'), meta: { title: '批次任务' } },
    { path: 'assets', name: 'v2-assets', component: () => import('@/v2/features/assets/AssetLibraryView.vue'), meta: { title: '素材库' } },
    { path: 'assets/picker', name: 'v2-asset-picker', component: () => import('@/v2/features/assets/AssetPickerDemoView.vue'), meta: { title: '素材选择器' } },
    { path: 'reference-videos', name: 'v2-reference-videos', component: () => import('@/v2/features/assets/ReferenceVideoView.vue'), meta: { title: '参考视频' } },
    { path: 'prompts', name: 'v2-prompts', component: () => import('@/v2/features/prompts/PromptLibraryView.vue'), meta: { title: '提示词库' } },
    { path: 'recycle-bin', name: 'v2-recycle', component: () => import('@/v2/features/assets/RecycleBinView.vue'), meta: { title: '回收站' } },
    { path: 'workflows', name: 'v2-workflows', component: () => import('@/views/WorkflowManageView.vue'), meta: { title: '工作流管理' } },
    { path: 'parameter-schemes', name: 'v2-schemes', component: () => import('@/v2/features/settings/ParameterSchemeView.vue'), meta: { title: '参数方案' } },
    { path: 'settings/generation-types', name: 'v2-generation-types', component: () => import('@/v2/features/generation-config/GenerationTypeListView.vue'), meta: { title: '生成类型配置', adminOnly: true } },
    { path: 'settings/ai', name: 'v2-ai-settings', component: () => import('@/v2/features/settings/AIProviderSettingsView.vue'), meta: { title: 'AI 模型配置', adminOnly: true } },
    { path: 'settings/image-providers', name: 'v2-image-providers', component: () => import('@/v2/features/settings/ImageProviderSettingsView.vue'), meta: { title: '图片模型配置', adminOnly: true } },
    { path: 'settings/generation-types/:id', name: 'v2-generation-type-editor', component: () => import('@/v2/features/generation-config/GenerationTypeConfigEditorView.vue'), meta: { title: '编辑生成类型', adminOnly: true } },
    { path: 'settings/nodes', name: 'v2-nodes', component: () => import('@/v2/features/runtime/RuntimeMonitorView.vue'), meta: { title: '运行监控', adminOnly: true } },
    { path: 'settings/users', name: 'v2-users', component: () => import('@/v2/features/settings/UserManagementView.vue'), meta: { title: '用户与权限', adminOnly: true } },
    { path: 'settings/system', name: 'v2-system-settings', component: () => import('@/views/SettingsView.vue'), meta: { title: '系统设置', adminOnly: true } },
    { path: 'settings/audit', name: 'v2-audit', component: () => import('@/v2/features/settings/AuditLogView.vue'), meta: { title: '审计日志', adminOnly: true } },
  ],
}
