<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { batchApi, genTypeApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import { flattenGenerationMenu, formatDate, statusMeta, type GenerationTypeItem, type TaskItem } from '@/v2/features/tasks/model'
type Batch={id:number;name:string;generation_type_id:number|null;source:string;submitted_at:string|null}
type Summary={state:string;total:number;success:number;failed:number;cancelled:number}
const batches=ref<Batch[]>([]);const types=ref<GenerationTypeItem[]>([]);const summaries=ref<Record<number,Summary>>({});const selected=ref<Batch|null>(null);const rows=ref<TaskItem[]>([]);const loading=ref(false);const retrying=ref(false)
function typeName(id:number|null){return types.value.find(v=>v.id===id)?.name||'未分类'} function progress(s:Summary){return s.total?Math.round((s.success+s.failed+s.cancelled)*100/s.total):0}
async function load(){loading.value=true;try{const [list,menu]=await Promise.all([batchApi.list(),genTypeApi.menu()]);batches.value=list;types.value=flattenGenerationMenu(menu);await Promise.all(list.map(async(b:Batch)=>{try{summaries.value[b.id]=await batchApi.status(b.id)}catch{}}))}finally{loading.value=false}}
async function open(batch:Batch){selected.value=batch;rows.value=await batchApi.rows(batch.id)} async function retry(){if(!selected.value)return;retrying.value=true;try{const result=await batchApi.retryFailed(selected.value.id);alert(`已重新排队 ${result.retried} 项失败任务`);await open(selected.value);await load()}finally{retrying.value=false}}
onMounted(load)
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge tone="info">批次执行</StatusBadge><h1>批次任务</h1><p>查看批次进度、任务行和失败重试</p></div><V2Button :disabled="loading" @click="load">刷新</V2Button></div><div class="batch-grid"><GlassCard v-for="batch in batches" :key="batch.id" interactive @click="open(batch)"><header><div><b>#{{ batch.id }} {{ batch.name||'未命名批次' }}</b><small>{{ typeName(batch.generation_type_id) }} · {{ batch.source }}</small></div><StatusBadge :tone="summaries[batch.id]?.state==='SUCCESS'?'success':summaries[batch.id]?.state==='FAILED'?'danger':'info'">{{ summaries[batch.id]?.state||'DRAFT' }}</StatusBadge></header><div class="progress"><i :style="{width:`${progress(summaries[batch.id]||{state:'',total:0,success:0,failed:0,cancelled:0})}%`}"/></div><footer><span>{{ progress(summaries[batch.id]||{state:'',total:0,success:0,failed:0,cancelled:0}) }}%</span><small>成功 {{ summaries[batch.id]?.success||0 }} · 失败 {{ summaries[batch.id]?.failed||0 }} · 总计 {{ summaries[batch.id]?.total||0 }}</small></footer></GlassCard><p v-if="!batches.length&&!loading" class="empty">暂无批次任务</p></div><GlassDrawer :open="!!selected" :title="selected?`批次 #${selected.id}`:'批次详情'" @close="selected=null"><div v-if="selected" class="batch-detail"><div class="detail-head"><div><h3>{{ selected.name||'未命名批次' }}</h3><p>{{ typeName(selected.generation_type_id) }} · 提交于 {{ formatDate(selected.submitted_at) }}</p></div><V2Button v-if="summaries[selected.id]?.failed" :disabled="retrying" variant="primary" @click="retry">{{ retrying?'处理中…':'失败项重试' }}</V2Button></div><div class="rows"><div v-for="row in rows" :key="row.id"><b>行 {{ row.row_no }} · 任务 #{{ row.id }}</b><StatusBadge :tone="statusMeta[row.status]?.tone">{{ statusMeta[row.status]?.label||row.status }}</StatusBadge><span>{{ row.params?.prompt||row.error||'无提示词' }}</span></div><p v-if="!rows.length">暂无任务行</p></div></div></GlassDrawer></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between}.heading h1{margin-top:14px}.batch-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.batch-grid .glass-card{cursor:pointer}.batch-grid header,.batch-grid footer{display:flex;align-items:center;justify-content:space-between;gap:12px}.batch-grid header>div{display:grid;gap:5px}.batch-grid small{color:var(--v2-text-muted)}.progress{height:8px;margin:22px 0 12px;overflow:hidden;background:var(--v2-surface-soft);border-radius:9px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--v2-primary),var(--v2-success));border-radius:inherit}.empty{grid-column:1/-1;padding:70px;text-align:center;color:var(--v2-text-muted)}.batch-detail{display:grid;gap:20px}.detail-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.detail-head h3,.detail-head p{margin:0}.detail-head p{margin-top:6px;color:var(--v2-text-muted)}.rows{display:grid;gap:8px}.rows>div{padding:12px;display:grid;grid-template-columns:1fr auto;gap:7px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:11px}.rows>div>span{grid-column:1/3;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--v2-text-muted);font-size:12px}@media(max-width:1050px){.batch-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.batch-grid{grid-template-columns:1fr}.detail-head{align-items:flex-start;flex-direction:column}}</style>
