<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { resourceApi, resourceFolderApi } from '@/api/modules'
import V2Button from './V2Button.vue'
import V2Field from './V2Field.vue'
import FolderTree from '@/v2/features/assets/FolderTree.vue'
import ResourceCard from '@/v2/features/assets/ResourceCard.vue'
import MediaViewer from './MediaViewer.vue'
import type { TaskOutput } from '@/v2/features/tasks/model'
import { flattenFolders, localDateKey, type FolderNode, type ResourceItem } from '@/v2/features/assets/model'
import { useResourceThumbs } from '@/v2/features/assets/useResourceThumbs'
const props=withDefaults(defineProps<{open:boolean;mediaType?:'image'|'video'|'audio';multiple?:boolean}>(),{mediaType:'image',multiple:false});const emit=defineEmits<{close:[];select:[ResourceItem[]]}>();const tree=ref<FolderNode[]>([]);const folderId=ref<number|null>(null);const expanded=ref(new Set<number>());const items=ref<ResourceItem[]>([]);const selected=ref(new Set<number>());const selectedItems=ref(new Map<number,ResourceItem>());const preview=ref<TaskOutput|null>(null);const keyword=ref('');const uploadInput=ref<HTMLInputElement|null>(null);const {thumbs,load:loadThumbs,clear}=useResourceThumbs();const flat=computed(()=>flattenFolders(tree.value));const currentFolder=computed(()=>flat.value.find(v=>v.id===folderId.value))
function openPreview(item:ResourceItem){preview.value={id:item.id,filename:item.filename,media_type:item.media_type,mime:item.mime,width:item.width,height:item.height,duration:item.duration}}
function ancestors(id:number|null){let n=flat.value.find(v=>v.id===id);const next=new Set(expanded.value);while(n?.parent_id){next.add(n.parent_id);n=flat.value.find(v=>v.id===n?.parent_id)}expanded.value=next}
async function init(){if(!props.open)return;tree.value=await resourceFolderApi.tree();const key=`task_results:${localDateKey()}`;folderId.value=flat.value.find(v=>v.system_key===key)?.id??flat.value.find(v=>v.system_key==='uploads')?.id??flat.value[0]?.id??null;ancestors(folderId.value);selected.value=new Set();selectedItems.value=new Map();await load()}
async function load(){if(!props.open)return;clear();items.value=await resourceApi.list({folder_id:folderId.value||undefined,media_type:props.mediaType,keyword:keyword.value||undefined,limit:200});void loadThumbs(items.value)}function toggleFolder(id:number){const next=new Set(expanded.value);next.has(id)?next.delete(id):next.add(id);expanded.value=next}function toggle(item:ResourceItem){const next=new Set(selected.value);const chosen=new Map(selectedItems.value);if(!props.multiple){next.clear();chosen.clear()}if(next.has(item.id)){next.delete(item.id);chosen.delete(item.id)}else{next.add(item.id);chosen.set(item.id,item)}selected.value=next;selectedItems.value=chosen}function confirm(){emit('select',[...selectedItems.value.values()]);emit('close')}
async function upload(files:FileList|null){if(!files?.length)return;for(const file of [...files]){const saved=await resourceApi.upload(file,props.mediaType,'input');if(folderId.value)await resourceApi.move(saved.id,folderId.value)}await load();if(uploadInput.value)uploadInput.value.value=''}
watch(()=>props.open,init);watch(folderId,load);let timer:ReturnType<typeof setTimeout>|null=null;watch(keyword,()=>{if(timer)clearTimeout(timer);timer=setTimeout(load,300)})
</script>
<template><Teleport to="body"><Transition name="picker"><div v-if="open" class="picker-layer v2-theme" role="dialog" aria-modal="true"><header><div><h2>选择{{ mediaType==='image'?'图片':mediaType==='video'?'视频':'音频' }}</h2><p>{{ multiple?'支持跨目录多选，选择结果会一直保留':'选择一个素材后点击确认' }}</p></div><button aria-label="关闭" @click="emit('close')">×</button></header><div class="toolbar"><V2Field label="搜索素材"><input v-model="keyword" placeholder="输入文件名"/></V2Field><div class="folder-name"><span>当前目录</span><b>{{ currentFolder?.name||'全部素材' }}</b></div><input ref="uploadInput" hidden type="file" :multiple="multiple" :accept="`${mediaType}/*`" @change="upload(($event.target as HTMLInputElement).files)"/><V2Button @click="uploadInput?.click()">上传到当前目录</V2Button></div><div class="picker-body"><aside><FolderTree :tree="tree" :current-id="folderId" :expanded="expanded" @select="folderId=$event" @toggle="toggleFolder"/></aside><main><ResourceCard v-for="item in items" :key="item.id" :item="item" :thumb="thumbs[item.id]" :selected="selected.has(item.id)" select-on-preview @open="openPreview(item)" @preview="openPreview(item)" @select="toggle(item)"/><p v-if="!items.length">没有符合条件的素材</p></main></div><footer><span>当前显示 {{ items.length }} 项 · 已选择 <b>{{ selected.size }}</b> 项</span><div><V2Button variant="ghost" @click="selected=new Set();selectedItems=new Map()">清空选择</V2Button><V2Button variant="ghost" @click="emit('close')">取消</V2Button><V2Button variant="primary" :disabled="!selected.size" @click="confirm">确认选择</V2Button></div></footer></div></Transition></Teleport><MediaViewer :open="!!preview" :output="preview" @close="preview=null"/></template>
<style scoped>.picker-layer{position:fixed;inset:clamp(8px,2vw,24px);z-index:1200;display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;color:var(--v2-text);background:rgba(7,13,24,.97);border:1px solid var(--v2-border);border-radius:18px;box-shadow:0 28px 80px rgba(0,0,0,.55);backdrop-filter:blur(20px);overflow:hidden}.picker-layer>header{padding:15px 20px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--v2-border)}header h2,header p{margin:0}header p{margin-top:4px;color:var(--v2-text-muted);font-size:12px}header>button{width:38px;height:38px;color:var(--v2-text);font-size:23px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:10px}.toolbar{padding:12px 16px;display:grid;grid-template-columns:minmax(260px,1fr) minmax(180px,.5fr) auto;align-items:end;gap:12px;border-bottom:1px solid var(--v2-border)}.folder-name{display:grid;gap:8px}.folder-name span{font-size:13px;font-weight:600}.folder-name b{min-height:42px;padding:10px 12px;background:rgba(3,12,25,.42);border:1px solid var(--v2-border);border-radius:9px}.picker-body{min-height:0;display:grid;grid-template-columns:260px minmax(0,1fr)}.picker-body aside{overflow:auto;padding:12px;border-right:1px solid var(--v2-border);background:rgba(255,255,255,.018)}.picker-body main{padding:14px;overflow:auto;align-content:start;display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:12px}.picker-body main p{grid-column:1/-1;color:var(--v2-text-muted)}footer{padding:12px 18px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--v2-border);color:var(--v2-text-muted)}footer>div{display:flex;gap:8px}.picker-enter-active,.picker-leave-active{transition:opacity .18s}.picker-enter-from,.picker-leave-to{opacity:0}@media(max-width:700px){.picker-layer{inset:0;border:0;border-radius:0}.toolbar{grid-template-columns:1fr auto}.folder-name{display:none}.picker-body{grid-template-columns:1fr;grid-template-rows:minmax(110px,25vh) minmax(0,1fr)}.picker-body aside{border-right:0;border-bottom:1px solid var(--v2-border)}.picker-body main{grid-template-columns:repeat(2,minmax(0,1fr));padding:10px;gap:8px}footer{align-items:flex-start;flex-direction:column}footer>div{width:100%}footer>div>*{flex:1}}</style>
