<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { getAccessToken } from '@/api/client'
import { resourceApi } from '@/api/modules'
import type { TaskOutput } from '@/v2/features/tasks/model'
import GlassDrawer from './GlassDrawer.vue'
import V2Button from './V2Button.vue'
import { formatDuration } from '@/v2/features/assets/model'
const props = defineProps<{ open: boolean; output: TaskOutput | null }>()
const emit = defineEmits<{ close: [] }>()
const url = ref(''); const loading = ref(false); const scale = ref(1); const x = ref(0); const y = ref(0); const dragging = ref(false); const metadata = ref<TaskOutput|null>(null)
let startX=0,startY=0,originX=0,originY=0
const isImage = computed(() => props.output?.media_type === 'image' || props.output?.mime.startsWith('image/'))
const mediaInfo = computed(() => { const output=metadata.value||props.output;if(!output)return[];const info:Array<{label:string;value:string}>=[];if(output.width&&output.height)info.push({label:output.media_type==='image'?'图片尺寸':'视频尺寸',value:`${output.width} × ${output.height}`});if((output.media_type==='video'||output.media_type==='audio')&&output.duration!=null)info.push({label:'时长',value:formatDuration(output.duration)});return info })
async function load() { if(url.value) URL.revokeObjectURL(url.value); url.value='';metadata.value=props.output;scale.value=1;x.value=0;y.value=0;if(!props.open||!props.output)return;loading.value=true;try{const [res,detail]=await Promise.all([fetch(resourceApi.fileUrl(props.output.id),{headers:{Authorization:`Bearer ${getAccessToken()||''}`}}),resourceApi.get(props.output.id).catch(()=>null)]);if(!res.ok)throw new Error();if(detail)metadata.value={...props.output,...detail};url.value=URL.createObjectURL(await res.blob())}finally{loading.value=false} }
watch(() => [props.open, props.output?.id], load)
function zoom(delta:number){scale.value=Math.min(5,Math.max(.25,scale.value+delta))} function reset(){scale.value=1;x.value=0;y.value=0}
function down(e:PointerEvent){if(!isImage.value)return;dragging.value=true;startX=e.clientX;startY=e.clientY;originX=x.value;originY=y.value;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
function move(e:PointerEvent){if(dragging.value){x.value=originX+e.clientX-startX;y.value=originY+e.clientY-startY}} function up(){dragging.value=false}
function download(){if(!url.value||!props.output)return;const link=document.createElement('a');link.href=url.value;link.download=props.output.filename||`resource-${props.output.id}`;document.body.appendChild(link);link.click();link.remove()}
onUnmounted(()=>{if(url.value)URL.revokeObjectURL(url.value)})
</script>
<template><GlassDrawer :open="open" :title="output?.filename || '媒体预览'" @close="emit('close')"><div v-if="loading" class="viewer-state">加载中…</div><div v-else-if="url" class="viewer"><div v-if="isImage" class="image-stage" @wheel.prevent="zoom($event.deltaY<0?.2:-.2)" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up"><img :src="url" :alt="output?.filename" :style="{transform:`translate(${x}px,${y}px) scale(${scale})`}" draggable="false" /></div><video v-else-if="output?.media_type==='video'" :src="url" controls autoplay playsinline /><audio v-else :src="url" controls autoplay /><div class="media-info"><span><small>类型</small><b>{{ output?.media_type==='image'?'图片':output?.media_type==='video'?'视频':'音频' }}</b></span><span v-for="item in mediaInfo" :key="item.label"><small>{{ item.label }}</small><b>{{ item.value }}</b></span><span v-if="!mediaInfo.length"><small>媒体信息</small><b>暂无尺寸或时长数据</b></span></div><div class="tools"><template v-if="isImage"><V2Button @click="zoom(-.25)">－</V2Button><span>{{ Math.round(scale*100) }}%</span><V2Button @click="zoom(.25)">＋</V2Button><V2Button variant="ghost" @click="reset">重置</V2Button></template><V2Button variant="primary" @click="download">⇩ 下载原文件</V2Button></div></div><div v-else class="viewer-state">资源加载失败</div></GlassDrawer></template>
<style scoped>.viewer-state{padding:48px 0;text-align:center;color:var(--v2-text-muted)}.viewer{display:grid;gap:14px}.image-stage{height:min(64vh,620px);overflow:hidden;display:grid;place-items:center;background:rgba(0,0,0,.28);border:1px solid var(--v2-border);border-radius:14px;touch-action:none;cursor:grab}.image-stage:active{cursor:grabbing}.image-stage img{max-width:92%;max-height:92%;object-fit:contain;transform-origin:center;user-select:none}video{width:100%;max-height:68vh;border-radius:14px;background:#000}audio{width:100%;margin-top:30px}.media-info{padding:10px;display:flex;flex-wrap:wrap;gap:8px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:11px}.media-info span{min-width:105px;display:grid;gap:4px}.media-info small{color:var(--v2-text-muted)}.media-info b{font-size:13px}.tools{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap}.tools>span{min-width:55px;text-align:center;color:var(--v2-text-muted)}</style>
