<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { resourceApi, resourceFolderApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
import FolderTree from './FolderTree.vue'
import ResourceCard from './ResourceCard.vue'
import ResourceDetailDrawer from './ResourceDetailDrawer.vue'
import { flattenFolders, localDateKey, type FolderNode, type ResourceItem } from './model'
import { useResourceThumbs } from './useResourceThumbs'
const PAGE=30;const tree=ref<FolderNode[]>([]);const currentId=ref<number|null>(null);const expanded=ref(new Set<number>());const items=ref<ResourceItem[]>([]);const selected=ref(new Set<number>());const media=ref('');const direction=ref('');const keyword=ref('');const loading=ref(false);const loadingMore=ref(false);const hasMore=ref(true);const detail=ref<ResourceItem|null>(null);const folderDialog=ref(false);const folderName=ref('');const editing=ref(false);const moveDialog=ref(false);const moveTarget=ref<number|null>(null);const uploadInput=ref<HTMLInputElement|null>(null);const {thumbs,load:loadThumbs,clear}=useResourceThumbs()
const flat=computed(()=>flattenFolders(tree.value));const current=computed(()=>flat.value.find(v=>v.id===currentId.value));const normalFolder=computed(()=>current.value?.folder_type==='normal')
function expandAncestors(id:number|null){const next=new Set(expanded.value);let node=flat.value.find(v=>v.id===id);while(node?.parent_id){next.add(node.parent_id);node=flat.value.find(v=>v.id===node?.parent_id)}expanded.value=next}
async function loadTree(defaultToday=false){tree.value=await resourceFolderApi.tree();if(defaultToday||!flat.value.some(v=>v.id===currentId.value)){const key=`task_results:${localDateKey()}`;currentId.value=flat.value.find(v=>v.system_key===key)?.id??flat.value.find(v=>v.system_key==='task_results')?.id??flat.value[0]?.id??null;expandAncestors(currentId.value)}}
async function load(reset=true){reset?loading.value=true:loadingMore.value=true;try{if(reset){items.value=[];clear()}const page=await resourceApi.list({folder_id:currentId.value||undefined,media_type:media.value||undefined,direction:direction.value||undefined,keyword:keyword.value||undefined,limit:PAGE,offset:items.value.length});items.value.push(...page);hasMore.value=page.length===PAGE;void loadThumbs(page)}finally{loading.value=false;loadingMore.value=false}}
function toggle(id:number){const next=new Set(expanded.value);next.has(id)?next.delete(id):next.add(id);expanded.value=next}function choose(id:number){currentId.value=id;selected.value=new Set()}function select(id:number){const next=new Set(selected.value);next.has(id)?next.delete(id):next.add(id);selected.value=next}
function openCreate(){editing.value=false;folderName.value='';folderDialog.value=true}function openRename(){if(!normalFolder.value)return;editing.value=true;folderName.value=current.value?.name||'';folderDialog.value=true}
async function saveFolder(){if(!folderName.value.trim())return;if(editing.value&&currentId.value)await resourceFolderApi.patch(currentId.value,{name:folderName.value});else await resourceFolderApi.create({name:folderName.value,parent_id:normalFolder.value?currentId.value:null});folderDialog.value=false;await loadTree()}
async function deleteFolder(){if(!normalFolder.value||!currentId.value||!confirm(`删除目录“${current.value?.name}”？`))return;await resourceFolderApi.delete(currentId.value);await loadTree(true);await load()}
function openMove(id?:number){if(id)selected.value=new Set([id]);if(!selected.value.size)return;moveTarget.value=currentId.value;moveDialog.value=true}async function move(){await resourceApi.batchMove([...selected.value],moveTarget.value);moveDialog.value=false;selected.value=new Set();await Promise.all([load(),loadTree()])}
async function uploadFiles(files:FileList|null){if(!files?.length)return;for(const file of [...files]){const type=file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'image';const saved=await resourceApi.upload(file,type,'input');if(currentId.value&&saved.folder_id!==currentId.value)await resourceApi.move(saved.id,currentId.value)}await Promise.all([load(),loadTree()]);if(uploadInput.value)uploadInput.value.value=''}
onMounted(async()=>{await loadTree(true);await load()});watch(currentId,()=>void load());let searchTimer:ReturnType<typeof setTimeout>|null=null;watch(keyword,()=>{if(searchTimer)clearTimeout(searchTimer);searchTimer=setTimeout(()=>void load(),350)})
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge tone="success">素材中心</StatusBadge><h1>素材库</h1><p>{{ current?.name||'目录' }} · 已加载 {{ items.length }} 项</p></div><div class="head-actions"><input ref="uploadInput" type="file" multiple accept="image/*,video/*,audio/*" hidden @change="uploadFiles(($event.target as HTMLInputElement).files)"/><V2Button @click="uploadInput?.click()">上传素材</V2Button><V2Button variant="primary" @click="openCreate">新建目录</V2Button></div></div><div class="library"><GlassCard padding="sm" class="folder-panel"><div class="folder-tools"><b>目录</b><button @click="expanded=new Set(flat.map(v=>v.id))">展开</button><button @click="expanded=new Set()">折叠</button></div><FolderTree :tree="tree" :current-id="currentId" :expanded="expanded" @select="choose" @toggle="toggle"/><div v-if="normalFolder" class="folder-actions"><V2Button variant="ghost" @click="openRename">重命名</V2Button><V2Button variant="danger" @click="deleteFolder">删除</V2Button></div></GlassCard><main><GlassCard padding="sm"><div class="filters"><V2Field label="搜索"><input v-model="keyword" placeholder="文件名称"/></V2Field><V2Field label="媒体类型"><select v-model="media" @change="load()"><option value="">全部</option><option value="image">图片</option><option value="video">视频</option><option value="audio">音频</option></select></V2Field><V2Field label="素材来源"><select v-model="direction" @change="load()"><option value="">全部</option><option value="input">上传素材</option><option value="output">任务结果</option></select></V2Field><V2Button v-if="selected.size" @click="openMove()">移动 {{ selected.size }} 项</V2Button></div></GlassCard><div class="resource-grid"><ResourceCard v-for="item in items" :key="item.id" :item="item" :thumb="thumbs[item.id]" :selected="selected.has(item.id)" @open="detail=item" @select="select(item.id)"/><p v-if="!items.length&&!loading" class="empty">当前目录没有素材</p></div><div class="load-more"><V2Button v-if="hasMore" :disabled="loadingMore" @click="load(false)">{{ loadingMore?'加载中…':'加载更多' }}</V2Button></div></main></div><ResourceDetailDrawer :open="!!detail" :resource="detail" @close="detail=null" @deleted="load();loadTree()"/><GlassDrawer :open="folderDialog" :title="editing?'重命名目录':'新建目录'" @close="folderDialog=false"><V2Field label="目录名称" required><input v-model="folderName" @keyup.enter="saveFolder"/></V2Field><div class="drawer-actions"><V2Button variant="primary" @click="saveFolder">保存</V2Button></div></GlassDrawer><GlassDrawer :open="moveDialog" title="移动素材" @close="moveDialog=false"><V2Field label="目标目录"><select v-model="moveTarget"><option v-for="folder in flat" :key="folder.id" :value="folder.id">{{ '　'.repeat(folder.depth) }}{{ folder.name }}</option></select></V2Field><div class="drawer-actions"><V2Button variant="primary" @click="move">确认移动</V2Button></div></GlassDrawer></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:14px}.heading h1{margin-top:14px}.head-actions,.folder-actions,.drawer-actions{display:flex;gap:8px}.library{display:grid;grid-template-columns:255px 1fr;gap:16px}.folder-panel{height:max-content;position:sticky;top:90px}.folder-tools{margin-bottom:10px;display:flex;align-items:center;gap:6px}.folder-tools b{flex:1}.folder-tools button{color:var(--v2-text-muted);background:transparent;border:0;cursor:pointer;font-size:11px}.folder-actions{margin-top:12px;padding-top:12px;border-top:1px solid var(--v2-border)}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;align-items:end;gap:10px}.resource-grid{margin-top:15px;display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:12px}.empty{grid-column:1/-1;padding:70px;text-align:center;color:var(--v2-text-muted)}.load-more{padding:20px;display:flex;justify-content:center}.drawer-actions{margin-top:18px}@media(max-width:1250px){.resource-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:980px){.library{grid-template-columns:220px 1fr}.resource-grid{grid-template-columns:repeat(3,1fr)}.filters{grid-template-columns:1fr 1fr}.filters>*:first-child{grid-column:span 2}}@media(max-width:700px){.heading{align-items:flex-start;flex-direction:column}.library{display:block}.folder-panel{position:static;margin-bottom:14px;max-height:280px;overflow:auto}.resource-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:390px){.resource-grid{grid-template-columns:1fr 1fr}.head-actions{width:100%}.head-actions>*{flex:1}}</style>
