<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { resourceApi, resourceFolderApi, genTypeApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
import FolderTree from './FolderTree.vue'
import ResourceCard from './ResourceCard.vue'
import ResourceDetailDrawer from './ResourceDetailDrawer.vue'
import { flattenGenerationMenu, type GenerationTypeItem } from '@/v2/features/tasks/model'
import { flattenFolders, localDateKey, type FolderNode, type ResourceItem } from './model'
import { useResourceThumbs } from './useResourceThumbs'
const PAGE=30;const tree=ref<FolderNode[]>([]);const currentId=ref<number|null>(null);const expanded=ref(new Set<number>());const items=ref<ResourceItem[]>([]);const selected=ref(new Set<number>());const media=ref('');const direction=ref('');const keyword=ref('');const loading=ref(false);const loadingMore=ref(false);const hasMore=ref(true);const detail=ref<ResourceItem|null>(null);const folderDialog=ref(false);const folderName=ref('');const editing=ref(false);const moveDialog=ref(false);const moveTarget=ref<number|null>(null);const deleting=ref(false);const folderPanelOpen=ref(false);const uploadInput=ref<HTMLInputElement|null>(null);const loadVersion={n:0};const {thumbs,load:loadThumbs,clear}=useResourceThumbs()
const router=useRouter()
const actionMenuOpen=ref(false);const actionType=ref<'image_ops'|'gen_video'>('image_ops');const genMenu=ref<GenerationTypeItem[]>([])
const selectedImageIds=computed(()=>[...selected.value].filter(id=>{const item=items.value.find(i=>i.id===id);return item?.media_type==='image'}))
const selectedVideoIds=computed(()=>[...selected.value].filter(id=>{const item=items.value.find(i=>i.id===id);return item?.media_type==='video'}))
const filteredGenMenu=computed(()=>{if(!genMenu.value.length)return[];if(actionType.value==='image_ops')return genMenu.value.filter(t=>t.media_type==='image'&&t.code!=='t2i');return genMenu.value.filter(t=>t.media_type==='video'&&t.code!=='t2v')})
async function loadGenMenu(){if(genMenu.value.length)return;try{const menu=await genTypeApi.menu();genMenu.value=flattenGenerationMenu(menu)}catch{}}
function openActionMenu(type:'image_ops'|'gen_video'){actionType.value=type;actionMenuOpen.value=true;void loadGenMenu()}
function pickGenType(item:GenerationTypeItem){if(!selectedImageIds.value.length)return;actionMenuOpen.value=false;const ids=selectedImageIds.value.join(',');selected.value=new Set();router.push({path:`/v2/generate/${item.code}`,query:{resource_ids:ids}})}
async function mergeVideos(){if(selectedVideoIds.value.length<2)return;if(!confirm(`确认合并选中的 ${selectedVideoIds.value.length} 个视频？\n按选中顺序拼接，保存为新视频。`))return;try{const result=await resourceApi.mergeVideos(selectedVideoIds.value);alert(`合并完成：${result.filename}`);selected.value=new Set();await Promise.all([load(),loadTree()])}catch(e:any){alert(e?.response?.data?.detail||e?.message||'合并失败')}}
const flat=computed(()=>flattenFolders(tree.value));const current=computed(()=>flat.value.find(v=>v.id===currentId.value));const normalFolder=computed(()=>current.value?.folder_type==='normal')
/** 可作为移动目标的目录（排除当前目录及其所有后代，仅 normal 类型） */
const movableFolderTargets = computed(() => {
  if (!current.value) return []
  const currentId = current.value.id
  const collectDescendants = (id: number): Set<number> => {
    const result = new Set<number>()
    const stack = [id]
    while (stack.length) {
      const fid = stack.pop()!
      for (const f of flat.value) {
        if (f.parent_id === fid && !result.has(f.id)) { result.add(f.id); stack.push(f.id) }
      }
    }
    return result
  }
  const exclude = new Set<number>([currentId, ...collectDescendants(currentId)])
  return flat.value.filter(f => !exclude.has(f.id) && f.folder_type === 'normal')
})
function expandAncestors(id:number|null){const next=new Set(expanded.value);let node=flat.value.find(v=>v.id===id);while(node?.parent_id){next.add(node.parent_id);node=flat.value.find(v=>v.id===node?.parent_id)}expanded.value=next}
async function loadTree(defaultToday=false){tree.value=await resourceFolderApi.tree();if(defaultToday||!flat.value.some(v=>v.id===currentId.value)){const key=`task_results:${localDateKey()}`;currentId.value=flat.value.find(v=>v.system_key===key)?.id??flat.value.find(v=>v.system_key==='task_results')?.id??flat.value[0]?.id??null;expandAncestors(currentId.value)}}
async function load(reset=true){const myRequest=loadVersion.n+1;loadVersion.n=myRequest;reset?loading.value=true:loadingMore.value=true;try{if(reset){items.value=[];clear()}const page=await resourceApi.list({folder_id:currentId.value||undefined,media_type:media.value||undefined,direction:direction.value||undefined,keyword:keyword.value||undefined,limit:PAGE,offset:reset?0:items.value.length});if(myRequest!==loadVersion.n)return;const unique=new Map<number,ResourceItem>();for(const item of items.value)unique.set(item.id,item);for(const item of page as ResourceItem[])unique.set(item.id,item);items.value=Array.from(unique.values());hasMore.value=page.length===PAGE;void loadThumbs(page)}finally{if(myRequest===loadVersion.n){loading.value=false;loadingMore.value=false}}}
function toggle(id:number){const next=new Set(expanded.value);next.has(id)?next.delete(id):next.add(id);expanded.value=next}function choose(id:number){currentId.value=id;selected.value=new Set();folderPanelOpen.value=false}function select(id:number){const next=new Set(selected.value);next.has(id)?next.delete(id):next.add(id);selected.value=next}
function openCreate(){editing.value=false;folderName.value='';folderDialog.value=true}function openRename(){if(!normalFolder.value)return;editing.value=true;folderName.value=current.value?.name||'';folderDialog.value=true}
const moveFolderDialog=ref(false)
const moveFolderTargetStr=ref('')
function openMoveFolder(){if(!normalFolder.value||!currentId.value)return;moveFolderTargetStr.value='';moveFolderDialog.value=true}
async function moveFolderConfirm(){
  if(!currentId.value)return
  const parentId=moveFolderTargetStr.value===''?null:Number(moveFolderTargetStr.value)
  try{
    await resourceFolderApi.patch(currentId.value,{parent_id:parentId})
    moveFolderDialog.value=false
    await loadTree(true)
    if(parentId){currentId.value=parentId}
    await load()
  }catch(e:any){alert(e?.response?.data?.detail||e?.message||'移动失败')}
}
async function saveFolder(){if(!folderName.value.trim())return;if(editing.value&&currentId.value)await resourceFolderApi.patch(currentId.value,{name:folderName.value});else await resourceFolderApi.create({name:folderName.value,parent_id:normalFolder.value?currentId.value:null});folderDialog.value=false;await loadTree()}
async function deleteFolder(){if(!normalFolder.value||!currentId.value||!confirm(`删除目录“${current.value?.name}”？`))return;await resourceFolderApi.delete(currentId.value);await loadTree(true);await load()}
function openMove(id?:number){if(id)selected.value=new Set([id]);if(!selected.value.size)return;moveTarget.value=currentId.value;moveDialog.value=true}async function move(){await resourceApi.batchMove([...selected.value],moveTarget.value);moveDialog.value=false;selected.value=new Set();await loadTree();await load()}
async function uploadFiles(files:FileList|null){if(!files?.length)return;for(const file of [...files]){const type=file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'image';const saved=await resourceApi.upload(file,type,'input');if(currentId.value&&saved.folder_id!==currentId.value)await resourceApi.move(saved.id,currentId.value)}await loadTree();await load();if(uploadInput.value)uploadInput.value.value=''}
async function batchDelete(){if(!selected.value.size)return;deleting.value=true;try{const result=await resourceApi.batchDelete([...selected.value]);const msg=`已移入回收站 ${result.deleted} 项${result.failed?.length?`，${result.failed.length} 项失败`:''}`;alert(msg);selected.value=new Set();await loadTree();await load()}catch(e:any){alert(e?.response?.data?.detail||e?.message||'删除失败')}finally{deleting.value=false}}
onMounted(async()=>{await loadTree(true);await load()});watch(currentId,()=>void load());let searchTimer:ReturnType<typeof setTimeout>|null=null;watch(keyword,()=>{if(searchTimer)clearTimeout(searchTimer);searchTimer=setTimeout(()=>void load(),350)})
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge tone="success">素材中心</StatusBadge><h1>素材库</h1><p>{{ current?.name||'目录' }} · 已加载 {{ items.length }} 项</p></div><div class="head-actions"><input ref="uploadInput" type="file" multiple accept="image/*,video/*,audio/*" hidden @change="uploadFiles(($event.target as HTMLInputElement).files)"/><V2Button @click="uploadInput?.click()">上传素材</V2Button><V2Button variant="primary" @click="openCreate">新建目录</V2Button></div></div><div class="library"><GlassCard padding="sm" class="folder-panel" :class="{open:folderPanelOpen}"><div class="folder-tools"><b>目录</b><button @click="expanded=new Set(flat.map(v=>v.id))">展开</button><button @click="expanded=new Set()">折叠</button></div><FolderTree :tree="tree" :current-id="currentId" :expanded="expanded" @select="choose" @toggle="toggle"/><div v-if="normalFolder" class="folder-actions"><V2Button variant="ghost" @click="openRename">重命名</V2Button><V2Button variant="ghost" @click="openMoveFolder">移动</V2Button><V2Button variant="danger" @click="deleteFolder">删除</V2Button></div></GlassCard><main><div class="mobile-folder-bar" @click="folderPanelOpen=!folderPanelOpen"><b>{{ current?.name||'选择目录' }}</b><span>{{ folderPanelOpen?'▲':'▼' }}</span></div><GlassCard padding="sm"><div class="filters"><V2Field label="搜索"><input v-model="keyword" placeholder="文件名称"/></V2Field><V2Field label="媒体类型"><select v-model="media" @change="load()"><option value="">全部</option><option value="image">图片</option><option value="video">视频</option><option value="audio">音频</option></select></V2Field><V2Field label="素材来源"><select v-model="direction" @change="load()"><option value="">全部</option><option value="input">上传素材</option><option value="output">任务结果</option></select></V2Field></div></GlassCard><div class="resource-grid"><ResourceCard v-for="item in items" :key="item.id" :item="item" :thumb="thumbs[item.id]" :selected="selected.has(item.id)" @open="detail=item" @select="select(item.id)"/><p v-if="!items.length&&!loading" class="empty">当前目录没有素材</p></div><div class="load-more"><V2Button v-if="hasMore" :disabled="loadingMore" @click="load(false)">{{ loadingMore?'加载中…':'加载更多' }}</V2Button></div></main></div>
<div v-if="selected.size" class="floating-bar"><span class="fb-count">已选 {{ selected.size }} 项</span><div class="fb-actions"><button @click="openMove()">移动</button><button v-if="selectedImageIds.length" @click="openActionMenu('image_ops')">图片操作</button><button v-if="selectedImageIds.length" @click="openActionMenu('gen_video')">生成视频</button><button v-if="selectedVideoIds.length>=2" @click="mergeVideos">合并视频</button><button class="fb-danger" :disabled="deleting" @click="batchDelete">{{ deleting?'删除中…':'移入回收站' }}</button><button class="fb-clear" @click="selected=new Set()">✕</button></div></div>
<ResourceDetailDrawer :open="!!detail" :resource="detail" @close="detail=null" @deleted="load();loadTree()"/><GlassDrawer :open="folderDialog" :title="editing?'重命名目录':'新建目录'" @close="folderDialog=false"><V2Field label="目录名称" required><input v-model="folderName" @keyup.enter="saveFolder"/></V2Field><div class="drawer-actions"><V2Button variant="primary" @click="saveFolder">保存</V2Button></div></GlassDrawer><GlassDrawer :open="moveDialog" title="移动素材" @close="moveDialog=false"><V2Field label="目标目录"><select v-model="moveTarget"><option v-for="folder in flat" :key="folder.id" :value="folder.id">{{ '　'.repeat(folder.depth) }}{{ folder.name }}</option></select></V2Field><div class="drawer-actions"><V2Button variant="primary" @click="move">确认移动</V2Button></div></GlassDrawer><GlassDrawer :open="moveFolderDialog" :title="`移动目录：${current?.name||''}`" @close="moveFolderDialog=false"><p class="move-folder-hint">选择新的父目录（不能选自身或子目录）：</p><select v-model="moveFolderTargetStr" class="folder-select"><option value="">— 顶层（无父目录） —</option><option v-for="folder in movableFolderTargets" :key="folder.id" :value="String(folder.id)">{{ '　'.repeat(folder.depth) }}{{ folder.name }}</option></select><div class="drawer-actions"><V2Button variant="primary" @click="moveFolderConfirm">确认移动</V2Button></div></GlassDrawer>
<div v-if="actionMenuOpen" class="action-menu-overlay" @click.self="actionMenuOpen=false"><div class="action-menu"><header><h3>{{ actionType==='image_ops'?'批量图片操作':'批量生成视频' }} · {{ selectedImageIds.length }} 张</h3><button @click="actionMenuOpen=false">✕</button></header><div class="action-list"><button v-for="item in filteredGenMenu" :key="item.id" class="action-item" @click="pickGenType(item)"><span class="action-name">{{ item.name }}</span><span class="action-code">{{ item.code }}</span></button><p v-if="!filteredGenMenu.length" class="action-empty">暂无可用的类型</p></div></div></div></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:14px}.heading h1{margin-top:14px}.head-actions,.folder-actions,.drawer-actions{display:flex;gap:8px}.library{display:grid;grid-template-columns:255px 1fr;gap:16px}.mobile-folder-bar{display:none}.folder-panel{height:max-content;position:sticky;top:90px}.folder-tools{margin-bottom:10px;display:flex;align-items:center;gap:6px}.folder-tools b{flex:1}.folder-tools button{color:var(--v2-text-muted);background:transparent;border:0;cursor:pointer;font-size:11px}.folder-actions{margin-top:12px;padding-top:12px;border-top:1px solid var(--v2-border)}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;align-items:end;gap:10px}.resource-grid{margin-top:15px;display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:12px}.empty{grid-column:1/-1;padding:70px;text-align:center;color:var(--v2-text-muted)}.load-more{padding:20px;display:flex;justify-content:center}.drawer-actions{margin-top:18px}
.move-folder-hint{margin:0 0 12px;color:var(--v2-text-muted);font-size:12px}
.folder-select{width:100%;min-height:160px;padding:8px 10px;color:var(--v2-text);background:rgba(3,8,17,.72);border:1px solid var(--v2-border);border-radius:9px;font-family:inherit;font-size:13px}@media(max-width:1250px){.resource-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:980px){.library{grid-template-columns:220px 1fr}.resource-grid{grid-template-columns:repeat(3,1fr)}.filters{grid-template-columns:1fr 1fr}.filters>*:first-child{grid-column:span 2}}@media(max-width:700px){.heading{align-items:flex-start;flex-direction:column}.library{display:block}.folder-panel{position:static;margin-bottom:0;max-height:0;overflow:hidden;transition:max-height .25s ease;border:0}.folder-panel.open{max-height:50vh;overflow:auto;margin-bottom:14px}.mobile-folder-bar{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;margin-bottom:14px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:12px;cursor:pointer;font-size:13px;color:var(--v2-text)}.mobile-folder-bar span{color:var(--v2-text-muted)}.resource-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:390px){.resource-grid{grid-template-columns:1fr 1fr}.head-actions{width:100%}.head-actions>*{flex:1}}
.action-menu-overlay{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;padding:16px}.action-menu{width:min(400px,92vw);max-height:70vh;background:#1a2238;border:1px solid rgba(130,149,255,.25);border-radius:14px;display:flex;flex-direction:column;overflow:hidden}.action-menu header{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(130,149,255,.15)}.action-menu header h3{margin:0;font-size:15px;color:#e8edff}.action-menu header button{color:#7a85a8;background:none;border:0;font-size:16px;cursor:pointer}.action-list{padding:8px;overflow-y:auto;display:grid;gap:4px}.action-item{padding:12px 14px;display:flex;align-items:center;justify-content:space-between;color:#c8d0ee;background:rgba(130,149,255,.06);border:1px solid rgba(130,149,255,.12);border-radius:10px;cursor:pointer;text-align:left}.action-item:hover{background:rgba(130,149,255,.16);border-color:rgba(130,149,255,.3)}.action-name{font-size:13px}.action-code{font-size:10px;color:#7a85a8}.action-empty{padding:30px;text-align:center;color:#7a85a8;font-size:13px}
.floating-bar{position:fixed;bottom:16px;left:50%;transform:translateX(-50%);z-index:100;display:flex;align-items:center;gap:12px;padding:10px 18px;background:rgba(13,20,36,.95);border:1px solid rgba(130,149,255,.3);border-radius:14px;box-shadow:0 8px 32px rgba(0,0,0,.4);backdrop-filter:blur(12px);max-width:calc(100vw - 32px)}.fb-count{font-size:13px;color:#c8d0ee;white-space:nowrap;display:flex;align-items:center;gap:12px}.fb-actions{display:flex;gap:5px;flex-wrap:wrap}.fb-actions button{padding:7px 12px;font-size:12px;color:#c8d0ee;background:rgba(130,149,255,.1);border:1px solid rgba(130,149,255,.2);border-radius:8px;cursor:pointer;white-space:nowrap}.fb-actions button:hover:not(:disabled){background:rgba(130,149,255,.2)}.fb-actions .fb-danger{color:#ffdce1;background:rgba(255,127,145,.1);border-color:rgba(255,127,145,.25)}.fb-actions .fb-danger:disabled{opacity:.5;cursor:not-allowed}.fb-actions .fb-clear{padding:7px 10px;color:#7a85a8;background:transparent;border:1px solid rgba(130,149,255,.15)}
@media(max-width:700px){.floating-bar{bottom:84px;left:8px;right:8px;transform:none;max-width:none;flex-direction:column;align-items:stretch;gap:8px}.fb-count{justify-content:space-between}.fb-actions{justify-content:center}.fb-actions button{flex:1}}</style>
