<script setup lang="ts">
import { onUnmounted, ref, watch } from 'vue'
import { getAccessToken } from '@/api/client'
import { useRouter } from 'vue-router'
import { resourceApi } from '@/api/modules'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import CopyButton from '@/v2/components/CopyButton.vue'
import MediaViewer from '@/v2/components/MediaViewer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import { formatDuration, formatSize, mediaLabel, type ResourceItem } from './model'
const props=defineProps<{open:boolean;resource:ResourceItem|null}>();const emit=defineEmits<{close:[];deleted:[]}>();const router=useRouter();const info=ref<any>(null);const loading=ref(false);const preview=ref(false);const thumb=ref('')
watch(()=>[props.open,props.resource?.id],async()=>{info.value=null;if(thumb.value)URL.revokeObjectURL(thumb.value);thumb.value='';if(!props.open||!props.resource)return;if(props.resource.media_type!=='audio'){try{const response=await fetch(resourceApi.thumbUrl(props.resource.id),{headers:{Authorization:`Bearer ${getAccessToken()||''}`}});if(response.ok)thumb.value=URL.createObjectURL(await response.blob())}catch{}}if(props.resource.direction==='output'){loading.value=true;try{info.value=await resourceApi.generationInfo(props.resource.id)}catch{}finally{loading.value=false}}})
onUnmounted(()=>{if(thumb.value)URL.revokeObjectURL(thumb.value)})
async function remove(){if(!props.resource||!confirm(`将“${props.resource.filename}”移入回收站？`))return;await resourceApi.delete(props.resource.id);emit('deleted');emit('close')}
function goTask(){if(!info.value)return;emit('close');router.push(`/v2/tasks?task=${info.value.task_id}`)}
</script>
<template><GlassDrawer :open="open" :title="resource?.filename||'素材详情'" @close="emit('close')"><div v-if="resource" class="detail"><button class="preview" @click="preview=true"><img v-if="thumb" :src="thumb"/><span v-else>♪</span><i>点击预览</i></button><div class="badges"><StatusBadge tone="info">{{ mediaLabel(resource.media_type) }}</StatusBadge><StatusBadge :tone="resource.direction==='output'?'success':'neutral'">{{ resource.direction==='output'?'任务结果':'上传素材' }}</StatusBadge></div><dl><div><dt>文件大小</dt><dd>{{ formatSize(resource.size) }}</dd></div><div><dt>分辨率</dt><dd>{{ resource.width&&resource.height?`${resource.width} × ${resource.height}`:'—' }}</dd></div><div><dt>时长</dt><dd>{{ formatDuration(resource.duration) }}</dd></div><div><dt>创建时间</dt><dd>{{ new Date(resource.created_at).toLocaleString() }}</dd></div><div><dt>素材 ID</dt><dd>#{{ resource.id }}</dd></div><div><dt>目录 ID</dt><dd>#{{ resource.folder_id||'—' }}</dd></div></dl><section v-if="loading"><p>生成参数加载中…</p></section><section v-else-if="info"><header><h3>生成信息</h3><V2Button variant="ghost" @click="goTask">查看任务 #{{ info.task_id }} →</V2Button></header><dl><div><dt>生成类型</dt><dd>{{ info.generation_type_name||'—' }}</dd></div><div><dt>工作流版本</dt><dd>#{{ info.workflow_version_id||'—' }}</dd></div><div><dt>批次</dt><dd>#{{ info.batch_id }} {{ info.batch_name }}</dd></div><div><dt>任务状态</dt><dd>{{ info.task_status }}</dd></div></dl><h4>生成参数</h4><div class="params"><div v-for="(value,key) in info.params" :key="String(key)"><div class="param-head"><b>{{ key }}</b><CopyButton v-if="typeof value==='string' && String(key).includes('prompt')" :text="String(value)" size="sm" /></div><pre>{{ typeof value==='object'?JSON.stringify(value,null,2):value }}</pre></div></div></section><div class="actions"><V2Button variant="primary" @click="preview=true">打开素材</V2Button><V2Button variant="danger" @click="remove">移入回收站</V2Button></div><MediaViewer :open="preview" :output="{id:resource.id,filename:resource.filename,media_type:resource.media_type,mime:resource.mime}" @close="preview=false"/></div></GlassDrawer></template>
<style scoped>.detail{display:grid;gap:16px}.preview{height:220px;position:relative;display:grid;place-items:center;color:var(--v2-text);background:rgba(0,0,0,.25);border:1px solid var(--v2-border);border-radius:14px;overflow:hidden;cursor:pointer}.preview img{width:100%;height:100%;object-fit:contain}.preview>span{font-size:60px}.preview i{position:absolute;bottom:10px;padding:5px 9px;background:rgba(0,0,0,.55);border-radius:8px;font-size:11px;font-style:normal}.badges,.actions{display:flex;gap:8px;flex-wrap:wrap}dl{margin:0;display:grid;grid-template-columns:1fr 1fr;gap:8px}dl div{padding:10px;background:var(--v2-surface-soft);border-radius:10px}dt{color:var(--v2-text-subtle);font-size:11px}dd{margin:4px 0 0;overflow-wrap:anywhere}section{padding-top:8px;border-top:1px solid var(--v2-border)}section header{display:flex;align-items:center;justify-content:space-between}h3,h4{margin:8px 0 12px}.params{display:grid;gap:7px}.params>div{padding:9px;background:var(--v2-surface-soft);border-radius:9px}.param-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.params b{font-size:11px;color:var(--v2-primary)}pre{margin:5px 0 0;white-space:pre-wrap;overflow-wrap:anywhere;color:var(--v2-text-muted);font-family:inherit;font-size:12px}@media(max-width:420px){dl{grid-template-columns:1fr}}</style>
