<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { dashboardApi } from '@/api/modules'
import { connectWs, onWsEvent } from '@/ws/client'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassPanel from '@/v2/components/GlassPanel.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import { formatDate, statusMeta, type DashboardSummary } from '@/v2/features/tasks/model'
const router=useRouter();const loading=ref(false);const summary=ref<DashboardSummary|null>(null);let off:(()=>void)|null=null;let timer:ReturnType<typeof setTimeout>|null=null
const empty:DashboardSummary={generated_at:'',tasks:{total:0,today:0,active:0,success:0,failed:0,success_rate:0,status_counts:{}},nodes:{total:0,online:0,capacity:0,items:[]},resources:{total:0,image:0,video:0,audio:0},workflows:{total:0,generation_types:0,configured_types:0},trend:[],recent_tasks:[]}
const data=computed(()=>summary.value||empty);const max=computed(()=>Math.max(1,...data.value.trend.map(v=>v.total)))
async function load(){loading.value=true;try{summary.value=await dashboardApi.summary()}finally{loading.value=false}}
function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(()=>void load(),500)}
onMounted(async()=>{await load();connectWs();off=onWsEvent(schedule)});onUnmounted(()=>{off?.();if(timer)clearTimeout(timer)})
</script>
<template><div class="v2-page"><div class="v2-page-heading hero"><div><StatusBadge tone="success">实时数据</StatusBadge><h1>系统概览</h1><p>任务调度、计算节点和数字资产的运行视图</p></div><div class="hero-actions"><small>更新于 {{ formatDate(data.generated_at) }}</small><V2Button :disabled="loading" @click="load">{{ loading?'刷新中…':'刷新数据' }}</V2Button></div></div>
<div class="metric-grid"><GlassCard interactive @click="router.push('/v2/tasks')"><span>今日任务</span><strong>{{ data.tasks.today }}</strong><small>累计 {{ data.tasks.total }} 项</small></GlassCard><GlassCard interactive @click="router.push('/v2/tasks')"><span>正在处理</span><strong>{{ data.tasks.active }}</strong><small>成功率 {{ data.tasks.success_rate }}%</small></GlassCard><GlassCard interactive><span>在线节点</span><strong>{{ data.nodes.online }}/{{ data.nodes.total }}</strong><small>并发容量 {{ data.nodes.capacity }}</small></GlassCard><GlassCard interactive @click="router.push('/v2/assets')"><span>素材资产</span><strong>{{ data.resources.total }}</strong><small>图 {{ data.resources.image }} · 视频 {{ data.resources.video }} · 音频 {{ data.resources.audio }}</small></GlassCard></div>
<div class="main-grid"><GlassPanel title="近 7 日任务趋势" :description="`今日成功率 ${data.tasks.success_rate}%`"><div class="trend"><div v-for="item in data.trend" :key="item.date" class="trend-col"><b>{{ item.total }}</b><div class="bar"><i class="success" :style="{height:`${item.success/max*150}px`}"/><i class="failed" :style="{height:`${item.failed/max*150}px`}"/><i :style="{height:`${Math.max(3,(item.total-item.success-item.failed)/max*150)}px`}"/></div><small>{{ item.date.slice(5) }}</small></div></div></GlassPanel><GlassPanel title="计算节点" :description="`${data.nodes.online} 个节点在线`"><div class="nodes"><div v-for="node in data.nodes.items" :key="node.id"><StatusBadge :tone="node.status==='online'?'success':'neutral'">{{ node.status==='online'?'在线':'离线' }}</StatusBadge><span><b>{{ node.name }}</b><small>并发 {{ node.max_concurrent }} · {{ formatDate(node.last_seen_at) }}</small></span></div><p v-if="!data.nodes.items.length">尚未配置节点</p></div></GlassPanel></div>
<GlassPanel title="最近任务" description="最新创建的任务" class="recent-panel"><template #actions><V2Button variant="ghost" @click="router.push('/v2/tasks')">全部任务 →</V2Button></template><div class="recent"><button v-for="task in data.recent_tasks" :key="task.id" @click="router.push(`/v2/tasks?task=${task.id}`)"><b>#{{ task.id }}</b><StatusBadge :tone="statusMeta[task.status]?.tone">{{ statusMeta[task.status]?.label||task.status }}</StatusBadge><span>{{ task.generation_type_name }}</span><em>{{ task.prompt||'无提示词' }}</em><time>{{ formatDate(task.created_at) }}</time></button><p v-if="!data.recent_tasks.length">暂无任务记录</p></div></GlassPanel></div></template>
<style scoped>.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:20px}.hero h1{margin-top:14px}.hero-actions{display:flex;align-items:center;gap:12px}.hero-actions small{color:var(--v2-text-muted)}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.metric-grid .glass-card{display:grid;gap:8px;cursor:pointer}.metric-grid span,.metric-grid small{color:var(--v2-text-muted)}.metric-grid strong{font-size:32px}.main-grid{margin-top:16px;display:grid;grid-template-columns:1.5fr 1fr;gap:16px}.trend{height:205px;display:grid;grid-template-columns:repeat(7,1fr);align-items:end;gap:10px}.trend-col{height:190px;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:6px}.trend-col>b,.trend-col small{font-size:11px;color:var(--v2-text-muted)}.bar{height:150px;width:min(38px,70%);display:flex;flex-direction:column-reverse;overflow:hidden;border-radius:7px 7px 2px 2px;background:var(--v2-surface-soft)}.bar i{display:block;background:var(--v2-info)}.bar .success{background:var(--v2-success)}.bar .failed{background:var(--v2-danger)}.nodes{display:grid;gap:10px}.nodes>div{padding:11px;display:flex;align-items:center;gap:12px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:12px}.nodes span{display:grid;gap:4px}.nodes small,.nodes p,.recent p{color:var(--v2-text-muted)}.recent-panel{margin-top:16px}.recent{display:grid}.recent button{min-height:48px;padding:8px 4px;display:grid;grid-template-columns:65px 85px 150px 1fr 170px;align-items:center;gap:10px;color:var(--v2-text);background:transparent;border:0;border-bottom:1px solid var(--v2-border);text-align:left;cursor:pointer}.recent em,.recent time{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--v2-text-muted);font-style:normal;font-size:12px}@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(2,1fr)}.main-grid{grid-template-columns:1fr}.recent button{grid-template-columns:60px 80px 1fr}.recent em,.recent time{display:none}}@media(max-width:540px){.hero{align-items:flex-start;flex-direction:column}.hero-actions{width:100%;justify-content:space-between}.metric-grid{grid-template-columns:1fr 1fr}.metric-grid .glass-card{padding:16px}.metric-grid strong{font-size:26px}.trend{gap:4px}.recent button{grid-template-columns:55px 82px 1fr}}</style>
