<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { shortDramaApi, type AIProvider } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'

const items=ref<AIProvider[]>([]),editing=ref<number|null>(null),saving=ref(false),testing=ref<number|null>(null),notice=ref(''),error=ref('')
const blank=()=>({name:'',provider:'openai_compatible',base_url:'https://api.openai.com/v1',model:'',api_key:'',enabled:true,is_default:false,timeout_seconds:120,max_tokens:8192})
const form=ref(blank())
async function load(){try{items.value=await shortDramaApi.aiProviders()}catch(event:any){error.value=event.response?.data?.detail||'AI 配置加载失败'}}
function edit(item?:AIProvider){editing.value=item?.id||null;form.value=item?{name:item.name,provider:item.provider,base_url:item.base_url,model:item.model,api_key:'',enabled:item.enabled,is_default:item.is_default,timeout_seconds:item.timeout_seconds,max_tokens:item.max_tokens}:blank();notice.value='';error.value=''}
async function save(){saving.value=true;error.value='';try{const body={...form.value,...(editing.value&&!form.value.api_key?{api_key:null}:{})};if(editing.value)await shortDramaApi.updateAIProvider(editing.value,body);else await shortDramaApi.createAIProvider(body);notice.value='AI 服务商配置已保存，API Key 已加密存储。';edit();await load()}catch(event:any){error.value=event.response?.data?.detail||'保存失败'}finally{saving.value=false}}
async function test(item:AIProvider){testing.value=item.id;error.value='';try{const result=await shortDramaApi.testAIProvider(item.id);notice.value=`${item.name} 连接成功：${result.model}，${result.latency_ms}ms`}catch(event:any){error.value=event.response?.data?.detail||'连接失败'}finally{testing.value=null}}
async function remove(item:AIProvider){if(!confirm(`删除“${item.name}”？已被任务使用的配置会改为停用。`))return;await shortDramaApi.deleteAIProvider(item.id);await load()}
onMounted(load)
</script>
<template><div class="v2-page ai-settings"><header><div><StatusBadge tone="info">短剧 AI</StatusBadge><h1>AI 模型配置</h1><p>管理小说分析与剧本改编使用的 OpenAI 兼容接口。密钥不会通过查询接口返回。</p></div><V2Button variant="primary" @click="edit()">＋ 新增服务商</V2Button></header><p v-if="error" class="banner error">{{ error }}</p><p v-if="notice" class="banner notice">{{ notice }}</p><div class="layout"><section class="providers"><GlassCard v-for="item in items" :key="item.id"><div class="provider-head"><div><h2>{{ item.name }}</h2><p>{{ item.base_url }}</p></div><StatusBadge :tone="item.enabled?'success':'neutral'">{{ item.enabled?'启用':'停用' }}</StatusBadge></div><dl><div><dt>模型</dt><dd>{{ item.model }}</dd></div><div><dt>密钥</dt><dd>{{ item.api_key_hint }}</dd></div><div><dt>超时</dt><dd>{{ item.timeout_seconds }} 秒</dd></div><div><dt>最大输出</dt><dd>{{ item.max_tokens }} tokens</dd></div></dl><StatusBadge v-if="item.is_default" tone="info">默认模型</StatusBadge><footer><V2Button variant="ghost" :disabled="testing===item.id" @click="test(item)">{{ testing===item.id?'测试中…':'连接测试' }}</V2Button><V2Button variant="ghost" @click="edit(item)">编辑</V2Button><V2Button variant="danger" @click="remove(item)">删除</V2Button></footer></GlassCard><p v-if="!items.length" class="empty">尚未配置 AI 服务商。配置完成前，小说转剧本只能使用本地规则。</p></section><GlassCard class="editor"><h2>{{ editing?'编辑服务商':'新增服务商' }}</h2><label>配置名称<input v-model="form.name" placeholder="例如：OpenAI 主模型"></label><label>API 地址<input v-model="form.base_url" placeholder="https://api.openai.com/v1"></label><label>模型名称<input v-model="form.model" placeholder="模型 ID"></label><label>API Key<input v-model="form.api_key" type="password" :placeholder="editing?'留空表示不修改':'本地免密接口可填写占位值'"></label><div class="two"><label>请求超时（秒）<input v-model.number="form.timeout_seconds" type="number" min="5" max="600"></label><label>最大输出 Token<input v-model.number="form.max_tokens" type="number" min="256"></label></div><label class="check"><input v-model="form.enabled" type="checkbox">启用该配置</label><label class="check"><input v-model="form.is_default" type="checkbox">设为小说转剧本默认模型</label><footer><V2Button variant="ghost" @click="edit()">重置</V2Button><V2Button variant="primary" :disabled="saving||!form.name||!form.base_url||!form.model" @click="save">{{ saving?'保存中…':'保存配置' }}</V2Button></footer></GlassCard></div></div></template>
<style scoped>.ai-settings{display:grid;gap:14px}.ai-settings>header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.ai-settings h1{margin:8px 0 3px;font-size:30px}.ai-settings header p,.provider-head p{margin:0;color:var(--v2-text-muted)}.banner{margin:0;padding:10px 13px;border-radius:10px}.banner.error{color:var(--v2-danger);background:rgba(255,80,110,.1)}.banner.notice{color:var(--v2-success);background:rgba(80,210,150,.08)}.layout{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:14px}.providers{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));align-content:start;gap:12px}.provider-head{display:flex;align-items:flex-start;justify-content:space-between}.provider-head h2,.editor h2{margin:0 0 7px}.providers dl{display:grid;grid-template-columns:1fr 1fr;gap:9px}.providers dl div{display:grid;gap:3px}.providers dt{color:var(--v2-text-muted);font-size:11px}.providers dd{margin:0;overflow:hidden;text-overflow:ellipsis}.providers footer,.editor footer{margin-top:14px;display:flex;justify-content:flex-end;gap:7px}.editor{display:grid;align-content:start;gap:12px}.editor label{display:grid;gap:5px;color:var(--v2-text-muted);font-size:12px}.editor input{width:100%;padding:10px;color:var(--v2-text);background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:9px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.editor .check{display:flex;align-items:center}.editor .check input{width:auto}.empty{padding:50px;text-align:center;color:var(--v2-text-muted)}@media(max-width:850px){.layout{grid-template-columns:1fr}.editor{order:-1}}@media(max-width:560px){.ai-settings>header{align-items:flex-start;flex-direction:column}.providers{grid-template-columns:1fr}.two{grid-template-columns:1fr}}</style>
