<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { imageProviderApi, type ImageProvider } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'

const items=ref<ImageProvider[]>([]),editing=ref<number|null>(null),saving=ref(false),testing=ref<number|null>(null),notice=ref(''),error=ref('')
const defaults={gemini_web2api:{base_url:'http://localhost:8083/v1',model:'gemini-image'},gemini_proxy:{base_url:'http://localhost:4982/openai/v1',model:'gemini-2.5-flash-image'}}
const blank=()=>({name:'Gemini Image',provider:'gemini_web2api' as ImageProvider['provider'],base_url:defaults.gemini_web2api.base_url,model:defaults.gemini_web2api.model,api_key:'',enabled:true,is_default:true,timeout_seconds:300,max_concurrency:1})
const form=ref(blank())
function providerChanged(){const value=defaults[form.value.provider];form.value.base_url=value.base_url;form.value.model=value.model}
async function load(){error.value='';try{items.value=await imageProviderApi.list()}catch(e:any){error.value=e.response?.data?.detail||'图片提供方加载失败'}}
function edit(item?:ImageProvider){editing.value=item?.id||null;form.value=item?{name:item.name,provider:item.provider,base_url:item.base_url,model:item.model,api_key:'',enabled:item.enabled,is_default:item.is_default,timeout_seconds:item.timeout_seconds,max_concurrency:item.max_concurrency}:blank();notice.value='';error.value=''}
async function save(){saving.value=true;error.value='';try{const body={...form.value,...(editing.value&&!form.value.api_key?{api_key:null}:{})};if(editing.value)await imageProviderApi.update(editing.value,body);else await imageProviderApi.create(body);notice.value='Gemini Image 配置已保存，密钥已加密存储。';edit();await load()}catch(e:any){error.value=e.response?.data?.detail||'保存失败'}finally{saving.value=false}}
async function test(item:ImageProvider){testing.value=item.id;error.value='';try{const result=await imageProviderApi.test(item.id);notice.value=`${item.name} 连接成功：${result.latency_ms}ms${result.model_available?'，模型可用':'，网关可达但模型列表未找到该模型'}`}catch(e:any){error.value=e.response?.data?.detail||'连接失败'}finally{testing.value=null}}
async function remove(item:ImageProvider){if(!confirm(`删除“${item.name}”？`))return;await imageProviderApi.remove(item.id);await load()}
onMounted(load)
</script>

<template><div class="v2-page provider-page"><header><div><StatusBadge tone="info">Gemini Image</StatusBadge><h1>图片模型配置</h1><p>每张模型配置卡都是独立执行通道，分别计算并发；图片尺寸统一读取系统维护项。</p></div><V2Button variant="primary" @click="edit()">＋ 新增提供方</V2Button></header><p v-if="error" class="banner error">{{ error }}</p><p v-if="notice" class="banner notice">{{ notice }}</p><div class="layout"><section class="providers"><GlassCard v-for="item in items" :key="item.id"><div class="provider-head"><div><h2>{{ item.name }}</h2><p>{{ item.provider==='gemini_web2api'?'Gemini Web2API':'Gemini WebAPI Proxy' }}</p></div><StatusBadge :tone="item.enabled?'success':'neutral'">{{ item.enabled?'启用':'停用' }}</StatusBadge></div><dl><div><dt>API 地址</dt><dd>{{ item.base_url }}</dd></div><div><dt>模型</dt><dd>{{ item.model }}</dd></div><div><dt>通道并发数</dt><dd>{{ item.max_concurrency }}</dd></div><div><dt>超时</dt><dd>{{ item.timeout_seconds }} 秒</dd></div></dl><StatusBadge v-if="item.is_default" tone="info">默认图片提供方</StatusBadge><footer><V2Button variant="ghost" :disabled="testing===item.id" @click="test(item)">{{ testing===item.id?'测试中…':'连接测试' }}</V2Button><V2Button variant="ghost" @click="edit(item)">编辑</V2Button><V2Button variant="danger" @click="remove(item)">删除</V2Button></footer></GlassCard><p v-if="!items.length" class="empty">尚未配置图片提供方。新增后可在混合生图和角色与场景中使用。</p></section><GlassCard class="editor"><h2>{{ editing?'编辑提供方':'新增提供方' }}</h2><label>配置名称<input v-model="form.name" placeholder="例如：Gemini 主图模型"></label><label>网关类型<select v-model="form.provider" @change="providerChanged"><option value="gemini_web2api">web2api（8083 / Chat Completions）</option><option value="gemini_proxy">proxy（4982 / Images API）</option></select></label><label>API 地址<input v-model="form.base_url"></label><label>模型名称<input v-model="form.model"></label><label>API Key<input v-model="form.api_key" type="password" :placeholder="editing?'留空表示不修改':'免密网关可留空'"></label><div class="two"><label>请求超时（秒）<input v-model.number="form.timeout_seconds" type="number" min="10" max="900"></label><label>该模型通道并发<input v-model.number="form.max_concurrency" type="number" min="1" max="32"></label></div><label class="check"><input v-model="form.enabled" type="checkbox">启用该配置</label><label class="check"><input v-model="form.is_default" type="checkbox">设为默认图片提供方</label><footer><V2Button variant="ghost" @click="edit()">重置</V2Button><V2Button variant="primary" :disabled="saving||!form.name||!form.base_url||!form.model" @click="save">{{ saving?'保存中…':'保存配置' }}</V2Button></footer></GlassCard></div></div></template>
<style scoped>.provider-page{display:grid;gap:14px}.provider-page>header{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.provider-page h1{margin:8px 0 3px;font-size:30px}.provider-page header p,.provider-head p{margin:0;color:var(--v2-text-muted)}.banner{margin:0;padding:10px 13px;border-radius:10px}.banner.error{color:var(--v2-danger);background:rgba(255,80,110,.1)}.banner.notice{color:var(--v2-success);background:rgba(80,210,150,.08)}.layout{display:grid;grid-template-columns:minmax(0,1fr) 400px;gap:14px}.providers{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));align-content:start;gap:12px}.provider-head{display:flex;justify-content:space-between;gap:10px}.provider-head h2,.editor h2{margin:0 0 7px}.providers dl{display:grid;grid-template-columns:1fr 1fr;gap:9px}.providers dt{color:var(--v2-text-muted);font-size:11px}.providers dd{margin:2px 0 0;overflow:hidden;text-overflow:ellipsis}.providers footer,.editor footer{margin-top:14px;display:flex;justify-content:flex-end;gap:7px}.editor{display:grid;align-content:start;gap:12px}.editor label{display:grid;gap:5px;color:var(--v2-text-muted);font-size:12px}.editor input,.editor select{width:100%;padding:10px;color:var(--v2-text);background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:9px}.editor .check{display:flex;align-items:center}.editor .check input{width:auto}.empty{padding:50px;text-align:center;color:var(--v2-text-muted)}@media(max-width:850px){.layout{grid-template-columns:1fr}.editor{order:-1}}</style>
