<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { genTypeApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
type Scheme={id:number;name:string;is_default:boolean;params:Record<string,any>}
const schemes=ref<Scheme[]>([]);const editing=ref<Scheme|null>(null);const saving=ref(false);const notice=ref('')
const resolutions=[['480p',1],['576p（默认）',2],['720p',3],['1080p',4]];const algorithms=[['vitpose',1],['sdpose',2],['wuwupose',3]]
function blank():Scheme{return{id:Date.now(),name:'',is_default:!schemes.value.length,params:{frame_rate:24,frame_load_cap:0,resolution:2,motion_algorithm:1,expression_enabled:false,expression_strength:1,camera_enabled:false,camera_strength:1,lora_strength:1}}}
async function load(){schemes.value=await genTypeApi.motionTransferSchemes()}
async function persist(next:Scheme[]){saving.value=true;try{schemes.value=await genTypeApi.saveMotionTransferSchemes(next);notice.value='参数方案已保存';editing.value=null}catch(e:any){notice.value=e.response?.data?.detail||'保存失败'}finally{saving.value=false}}
async function save(){if(!editing.value?.name.trim()){notice.value='请输入方案名称';return}let next=schemes.value.map(v=>({...v,is_default:editing.value?.is_default?false:v.is_default}));const index=next.findIndex(v=>v.id===editing.value!.id);index>=0?next.splice(index,1,editing.value):next.push(editing.value);await persist(next)}
async function setDefault(id:number){await persist(schemes.value.map(v=>({...v,is_default:v.id===id})))}
async function remove(id:number){if(schemes.value.length<=1){notice.value='至少保留一个参数方案';return}if(confirm('确定删除这个参数方案？'))await persist(schemes.value.filter(v=>v.id!==id))}
onMounted(load)
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge tone="info">动作迁移</StatusBadge><h1>参数方案</h1><p>统一维护帧率、分辨率、动作算法、表情、运镜与 Lora 强度；生成页只需选择方案。</p></div><V2Button variant="primary" @click="editing=blank()">新增方案</V2Button></div><div v-if="notice" class="notice">{{ notice }}</div><div class="scheme-grid"><GlassCard v-for="scheme in schemes" :key="scheme.id"><header><div><h2>{{ scheme.name }}</h2><StatusBadge v-if="scheme.is_default" tone="success">默认</StatusBadge></div><span>#{{ scheme.id }}</span></header><dl><div><dt>帧率</dt><dd>{{ scheme.params.frame_rate }} fps</dd></div><div><dt>加载帧数上限</dt><dd>{{ scheme.params.frame_load_cap||'不限' }}</dd></div><div><dt>分辨率</dt><dd>{{ resolutions.find(v=>v[1]===scheme.params.resolution)?.[0]||scheme.params.resolution }}</dd></div><div><dt>动作算法</dt><dd>{{ algorithms.find(v=>v[1]===scheme.params.motion_algorithm)?.[0]||scheme.params.motion_algorithm }}</dd></div><div><dt>表情 / 运镜</dt><dd>{{ scheme.params.expression_enabled?'开启':'关闭' }} / {{ scheme.params.camera_enabled?'开启':'关闭' }}</dd></div><div><dt>Lora 强度</dt><dd>{{ scheme.params.lora_strength }}</dd></div></dl><footer><V2Button v-if="!scheme.is_default" variant="ghost" @click="setDefault(scheme.id)">设为默认</V2Button><V2Button @click="editing=JSON.parse(JSON.stringify(scheme))">编辑</V2Button><V2Button variant="danger" @click="remove(scheme.id)">删除</V2Button></footer></GlassCard></div><GlassDrawer :open="!!editing" title="动作迁移参数方案" @close="editing=null"><div v-if="editing" class="editor"><V2Field label="方案名称" required><input v-model="editing.name"/></V2Field><V2Field label="帧率"><input v-model.number="editing.params.frame_rate" type="number" min="1" max="120"/></V2Field><V2Field label="加载帧数上限"><input v-model.number="editing.params.frame_load_cap" type="number" min="0"/></V2Field><V2Field label="分辨率"><select v-model.number="editing.params.resolution"><option v-for="item in resolutions" :key="item[1]" :value="item[1]">{{ item[0] }}</option></select></V2Field><V2Field label="动作算法"><select v-model.number="editing.params.motion_algorithm"><option v-for="item in algorithms" :key="item[1]" :value="item[1]">{{ item[0] }}</option></select></V2Field><V2Field label="Lora 强度"><input v-model.number="editing.params.lora_strength" type="number" min="0" max="2" step=".05"/></V2Field><V2Field label="表情强度"><input v-model.number="editing.params.expression_strength" type="number" min="0" max="2" step=".05"/></V2Field><V2Field label="运镜强度"><input v-model.number="editing.params.camera_strength" type="number" min="0" max="2" step=".05"/></V2Field><label class="check"><input v-model="editing.params.expression_enabled" type="checkbox"/>开启表情</label><label class="check"><input v-model="editing.params.camera_enabled" type="checkbox"/>开启运镜</label><label class="check"><input v-model="editing.is_default" type="checkbox"/>设为默认方案</label><V2Button variant="primary" :disabled="saving" @click="save">{{ saving?'保存中…':'保存方案' }}</V2Button></div></GlassDrawer></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:16px}.heading h1{margin-top:14px}.notice{margin-bottom:13px;padding:11px;color:var(--v2-text-muted);background:var(--v2-surface-soft);border-radius:10px}.scheme-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.scheme-grid header,.scheme-grid header>div,.scheme-grid footer{display:flex;align-items:center;justify-content:space-between;gap:8px}.scheme-grid h2{margin:0;font-size:17px}.scheme-grid header>span{color:var(--v2-text-subtle)}dl{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:20px 0}dl div{padding:9px;background:var(--v2-surface-soft);border-radius:9px}dt{color:var(--v2-text-subtle);font-size:11px}dd{margin:5px 0 0;font-weight:600}.editor{display:grid;grid-template-columns:1fr 1fr;gap:12px}.editor>:first-child,.editor>:last-child{grid-column:1/3}.check{min-height:42px;display:flex;align-items:center;gap:8px}@media(max-width:1050px){.scheme-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.heading{align-items:flex-start;flex-direction:column}.scheme-grid{grid-template-columns:1fr}.editor{grid-template-columns:1fr}.editor>:first-child,.editor>:last-child{grid-column:auto}}</style>
