<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { userApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
type User={id:number;username:string;role:string;status:string;created_at?:string}
const users=ref<User[]>([]);const loading=ref(false);const error=ref('');const creating=ref(false);const form=ref({username:'',password:'',role:'user'})
async function load(){loading.value=true;try{users.value=await userApi.list()}catch(e:any){error.value=e.response?.data?.detail||'加载用户失败'}finally{loading.value=false}}
async function create(){if(!form.value.username||!form.value.password){error.value='请输入用户名和密码';return}creating.value=true;try{await userApi.create(form.value);form.value={username:'',password:'',role:'user'};await load()}catch(e:any){error.value=e.response?.data?.detail||'创建失败'}finally{creating.value=false}}
async function patch(user:User,body:any){try{await userApi.patch(user.id,body);await load()}catch(e:any){error.value=e.response?.data?.detail||'更新失败'}}
onMounted(load)
</script>
<template><div class="v2-page"><div class="v2-page-heading"><StatusBadge tone="info">管理员</StatusBadge><h1>用户与权限</h1><p>创建账号并维护角色、启用状态和密码。</p></div><div v-if="error" class="error">{{ error }}</div><div class="layout"><GlassCard><h2>新增用户</h2><div class="form"><V2Field label="用户名" required><input v-model="form.username" autocomplete="off"/></V2Field><V2Field label="初始密码" required><input v-model="form.password" type="password"/></V2Field><V2Field label="角色"><select v-model="form.role"><option value="user">普通用户</option><option value="admin">管理员</option></select></V2Field><V2Button variant="primary" :disabled="creating" @click="create">{{ creating?'创建中…':'创建用户' }}</V2Button></div></GlassCard><GlassCard><header><h2>用户列表</h2><V2Button variant="ghost" :disabled="loading" @click="load">刷新</V2Button></header><div class="users"><article v-for="user in users" :key="user.id"><div><b>{{ user.username }}</b><small>#{{ user.id }} · {{ user.created_at||'本地账号' }}</small></div><select :value="user.role" @change="patch(user,{role:($event.target as HTMLSelectElement).value})"><option value="user">普通用户</option><option value="admin">管理员</option></select><StatusBadge :tone="user.status==='active'?'success':'neutral'">{{ user.status==='active'?'已启用':'已停用' }}</StatusBadge><V2Button variant="ghost" @click="patch(user,{status:user.status==='active'?'disabled':'active'})">{{ user.status==='active'?'停用':'启用' }}</V2Button></article></div></GlassCard></div></div></template>
<style scoped>.v2-page-heading h1{margin-top:14px}.error{margin-bottom:14px;padding:12px;color:var(--v2-danger);background:rgba(255,127,145,.1);border-radius:11px}.layout{display:grid;grid-template-columns:330px 1fr;gap:14px}.glass-card h2{margin:0 0 16px;font-size:17px}.glass-card>header{display:flex;align-items:center;justify-content:space-between}.form{display:grid;gap:12px}.users{display:grid;gap:8px}.users article{padding:11px;display:grid;grid-template-columns:1fr 140px 85px auto;align-items:center;gap:10px;background:var(--v2-surface-soft);border:1px solid var(--v2-border);border-radius:11px}.users article>div{display:grid;gap:5px}.users small{color:var(--v2-text-subtle)}select{min-height:38px;padding:0 9px;color:var(--v2-text);background:rgba(3,12,25,.42);border:1px solid var(--v2-border);border-radius:9px}@media(max-width:850px){.layout{grid-template-columns:1fr}.users article{grid-template-columns:1fr auto}.users article>div{grid-column:1/3}}</style>
