<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { promptApi } from '@/api/modules'
import GlassCard from '@/v2/components/GlassCard.vue'
import GlassDrawer from '@/v2/components/GlassDrawer.vue'
import StatusBadge from '@/v2/components/StatusBadge.vue'
import V2Button from '@/v2/components/V2Button.vue'
import V2Field from '@/v2/components/V2Field.vue'
const prompts=ref<any[]>([]);const categories=ref<any[]>([]);const keyword=ref('');const category=ref('');const editor=ref(false);const categoryEditor=ref(false);const selected=ref<any>(null);const categoryName=ref('');const form=reactive({name:'',content:'',negative_content:'',category_id:null as number|null,remark:'',tags:''})
async function load(){prompts.value=await promptApi.list({keyword:keyword.value||undefined,category_id:category.value||undefined});categories.value=await promptApi.listCategories()}function open(item?:any){selected.value=item||null;Object.assign(form,item?{...item,tags:(item.tags||[]).join(', ')}:{name:'',content:'',negative_content:'',category_id:null,remark:'',tags:''});editor.value=true}async function save(){const body={...form,tags:form.tags.split(',').map(v=>v.trim()).filter(Boolean)};selected.value?await promptApi.patch(selected.value.id,body):await promptApi.create(body);editor.value=false;await load()}async function remove(id:number){if(!confirm('确定删除该提示词？'))return;await promptApi.remove(id);await load()}async function addCategory(){if(!categoryName.value.trim())return;await promptApi.createCategory(categoryName.value);categoryName.value='';categoryEditor.value=false;await load()}let timer:ReturnType<typeof setTimeout>|null=null;function search(){if(timer)clearTimeout(timer);timer=setTimeout(load,300)}onMounted(load)
</script>
<template><div class="v2-page"><div class="v2-page-heading heading"><div><StatusBadge tone="info">参考内容</StatusBadge><h1>提示词库</h1><p>分类管理和复用常用正向、负向提示词。</p></div><div><V2Button @click="categoryEditor=true">添加分类</V2Button><V2Button variant="primary" @click="open()">添加提示词</V2Button></div></div><GlassCard padding="sm"><div class="filters"><V2Field label="搜索"><input v-model="keyword" placeholder="名称或内容" @input="search"/></V2Field><V2Field label="分类"><select v-model="category" @change="load"><option value="">全部分类</option><option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option></select></V2Field></div></GlassCard><div class="prompt-grid"><GlassCard v-for="item in prompts" :key="item.id" interactive><header><b>{{ item.name }}</b><StatusBadge>{{ categories.find(v=>v.id===item.category_id)?.name||'未分类' }}</StatusBadge></header><p>{{ item.content }}</p><details v-if="item.negative_content"><summary>负面提示词</summary><p>{{ item.negative_content }}</p></details><footer><span>{{ (item.tags||[]).join(' · ') }}</span><div><button @click="open(item)">编辑</button><button class="danger" @click="remove(item.id)">删除</button></div></footer></GlassCard><p v-if="!prompts.length" class="empty">暂无提示词</p></div><GlassDrawer :open="editor" :title="selected?'编辑提示词':'添加提示词'" @close="editor=false"><div class="form"><V2Field label="名称" required><input v-model="form.name"/></V2Field><V2Field label="分类"><select v-model="form.category_id"><option :value="null">未分类</option><option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option></select></V2Field><V2Field label="提示词正文" required><textarea v-model="form.content" rows="5"/></V2Field><V2Field label="负面提示词"><textarea v-model="form.negative_content" rows="3"/></V2Field><V2Field label="标签" hint="使用英文逗号分隔"><input v-model="form.tags"/></V2Field><V2Field label="备注"><input v-model="form.remark"/></V2Field><V2Button variant="primary" @click="save">保存</V2Button></div></GlassDrawer><GlassDrawer :open="categoryEditor" title="添加分类" @close="categoryEditor=false"><V2Field label="分类名称"><input v-model="categoryName" @keyup.enter="addCategory"/></V2Field><div class="save-cat"><V2Button variant="primary" @click="addCategory">保存</V2Button></div></GlassDrawer></div></template>
<style scoped>.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:12px}.heading h1{margin-top:14px}.heading>div:last-child{display:flex;gap:8px}.filters{display:grid;grid-template-columns:2fr 1fr;gap:10px}.prompt-grid{margin-top:14px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.prompt-grid header,.prompt-grid footer{display:flex;align-items:center;justify-content:space-between;gap:10px}.prompt-grid p{color:var(--v2-text-muted);line-height:1.7}.prompt-grid details{color:var(--v2-warning);font-size:12px}.prompt-grid footer{padding-top:12px;border-top:1px solid var(--v2-border)}.prompt-grid footer span{color:var(--v2-text-subtle);font-size:11px}.prompt-grid footer button{color:var(--v2-text-muted);background:transparent;border:0;cursor:pointer}.prompt-grid footer .danger{color:var(--v2-danger)}.empty{grid-column:1/-1;text-align:center}.form{display:grid;gap:14px}.save-cat{margin-top:16px}@media(max-width:1000px){.prompt-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.heading{align-items:flex-start;flex-direction:column}.prompt-grid{grid-template-columns:1fr}}</style>
